-- Script simplificado para asignar artículos huérfanos
-- Ejecutar en lotes separados

-- Lote 1: Asignar a radiocinconoticias
INSERT OR IGNORE INTO ARTICULOS_SITIO_RADIOCINCONOTICIAS (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 
  'orphan-' || ap.ID || '-radio',
  ap.ID,
  datetime('now'),
  0,
  NULL,
  NULL
FROM ARTICULOS_PARAFRASEADOS ap
WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_RADIOCINCONOTICIAS)
ORDER BY ap.FECHA_PUBLICACION DESC
LIMIT 6;

-- Lote 2: Asignar a centralmexico
INSERT OR IGNORE INTO ARTICULOS_SITIO_CENTRALMEXICO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 
  'orphan-' || ap.ID || '-central',
  ap.ID,
  datetime('now'),
  0,
  NULL,
  NULL
FROM ARTICULOS_PARAFRASEADOS ap
WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_CENTRALMEXICO)
ORDER BY ap.FECHA_PUBLICACION DESC
LIMIT 6;

-- Lote 3: Asignar a tvmexico
INSERT OR IGNORE INTO ARTICULOS_SITIO_TVMEXICO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 
  'orphan-' || ap.ID || '-tv',
  ap.ID,
  datetime('now'),
  0,
  NULL,
  NULL
FROM ARTICULOS_PARAFRASEADOS ap
WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_TVMEXICO)
ORDER BY ap.FECHA_PUBLICACION DESC
LIMIT 6;

-- Lote 4: Asignar a cbnnoticias
INSERT OR IGNORE INTO ARTICULOS_SITIO_CBNNOTICIAS (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 
  'orphan-' || ap.ID || '-cbn',
  ap.ID,
  datetime('now'),
  0,
  NULL,
  NULL
FROM ARTICULOS_PARAFRASEADOS ap
WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_CBNNOTICIAS)
ORDER BY ap.FECHA_PUBLICACION DESC
LIMIT 6;

-- Lote 5: Asignar a mexicoinformado
INSERT OR IGNORE INTO ARTICULOS_SITIO_MEXICOINFORMADO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 
  'orphan-' || ap.ID || '-mexinfo',
  ap.ID,
  datetime('now'),
  0,
  NULL,
  NULL
FROM ARTICULOS_PARAFRASEADOS ap
WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_MEXICOINFORMADO)
ORDER BY ap.FECHA_PUBLICACION DESC
LIMIT 6;

SELECT 'Lotes 1-5 completados' as status;
