-- Lote 6-10: Continuar asignación
-- Lote 6: nodoinformativo
INSERT OR IGNORE INTO ARTICULOS_SITIO_NODOINFORMATIVO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 'orphan-' || ap.ID || '-nodo', ap.ID, datetime('now'), 0, NULL, NULL
FROM ARTICULOS_PARAFRASEADOS ap WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_NODOINFORMATIVO)
ORDER BY ap.FECHA_PUBLICACION DESC LIMIT 6;

-- Lote 7: bitacoraurbana
INSERT OR IGNORE INTO ARTICULOS_SITIO_BITACORAURBANA (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 'orphan-' || ap.ID || '-bitacora', ap.ID, datetime('now'), 0, NULL, NULL
FROM ARTICULOS_PARAFRASEADOS ap WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_BITACORAURBANA)
ORDER BY ap.FECHA_PUBLICACION DESC LIMIT 6;

-- Lote 8: reportecentralmx
INSERT OR IGNORE INTO ARTICULOS_SITIO_REPORTECENTRALMX (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 'orphan-' || ap.ID || '-reporte', ap.ID, datetime('now'), 0, NULL, NULL
FROM ARTICULOS_PARAFRASEADOS ap WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_REPORTECENTRALMX)
ORDER BY ap.FECHA_PUBLICACION DESC LIMIT 6;

-- Lote 9: verticenoticias
INSERT OR IGNORE INTO ARTICULOS_SITIO_VERTICENOTICIAS (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 'orphan-' || ap.ID || '-vertice', ap.ID, datetime('now'), 0, NULL, NULL
FROM ARTICULOS_PARAFRASEADOS ap WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_VERTICENOTICIAS)
ORDER BY ap.FECHA_PUBLICACION DESC LIMIT 6;

-- Lote 10: noticiasobjetivo
INSERT OR IGNORE INTO ARTICULOS_SITIO_NOTICIASOBJETIVO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION, FB_PUBLICADO, FB_FECHA, FB_POST_ID)
SELECT 'orphan-' || ap.ID || '-objetivo', ap.ID, datetime('now'), 0, NULL, NULL
FROM ARTICULOS_PARAFRASEADOS ap WHERE ap.ESTADO = 'PUBLICADO'
AND ap.ID NOT IN (SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_NOTICIASOBJETIVO)
ORDER BY ap.FECHA_PUBLICACION DESC LIMIT 6;

SELECT 'Lotes 6-10 completados' as status;
