-- Limpieza de Duplicados y Categorización
-- Fecha: 2026-03-10

-- ============================================================
-- 1. ELIMINAR DUPLICADOS (mantener el más reciente)
-- ============================================================

-- Crear tabla temporal con duplicados a eliminar
CREATE TEMPORARY TABLE duplicados_a_eliminar AS
SELECT p1.ID
FROM ARTICULOS_PARAFRASEADOS p1
INNER JOIN ARTICULOS_PARAFRASEADOS p2 
  ON p1.SLUG = p2.SLUG 
  AND p1.ID != p2.ID
  AND p1.FECHA_PUBLICACION < p2.FECHA_PUBLICACION
WHERE p1.ESTADO = 'PUBLICADO';

-- Eliminar duplicados de ARTICULOS_SITIO_* primero (por foreign key)
DELETE FROM ARTICULOS_SITIO_RADIOCINCONOTICIAS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_CENTRALMEXICO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_TVMEXICO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_CBNNOTICIAS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_MEXICOINFORMADO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_NODOINFORMATIVO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_BITACORAURBANA WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_REPORTECENTRALMX WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_VERTICENOTICIAS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_NOTICIASOBJETIVO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_BOOMINFORMATIVO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_CAPITALPRESS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_DIARIOEXPRESS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_ELPULSOMEXICANO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_ENFOQUECAPITAL WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_ENFOQUEDIRECTO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_FORMULACDMX WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_MEXICANTIMES WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_MEXICO360NOTICIAS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_MRADIO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_NOTICIASHORIZONTE WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_PULSODIARIO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_PUNTOCLAVE WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_PUNTONOTICIAS WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_RADARINFORMATIVO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_REPORTEDIARIO WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);
DELETE FROM ARTICULOS_SITIO_TELEVISIONABC WHERE ID_PARAFRASEADO IN (SELECT ID FROM duplicados_a_eliminar);

-- Eliminar duplicados de ARTICULOS_PARAFRASEADOS
DELETE FROM ARTICULOS_PARAFRASEADOS WHERE ID IN (SELECT ID FROM duplicados_a_eliminar);

-- Limpiar tabla temporal
DROP TABLE duplicados_a_eliminar;

-- ============================================================
-- 2. ACTUALIZAR CATEGORÍAS
-- ============================================================

-- Actualizar a NACIONALES (noticias generales de México)
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'NACIONAL'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%México%' OR CONTENIDO LIKE '%CDMX%' OR CONTENIDO LIKE '%gobierno%' OR
    CONTENIDO LIKE '%presidente%' OR CONTENIDO LIKE '%congreso%' OR CONTENIDO LIKE '%senado%' OR
    CONTENIDO LIKE '%Sheinbaum%' OR CONTENIDO LIKE '%AMLO%' OR CONTENIDO LIKE '%Morena%'
  );

-- Actualizar a POLÍTICA
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'POLITICA'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%elecciones%' OR CONTENIDO LIKE '%voto%' OR CONTENIDO LIKE '%partido%' OR
    CONTENIDO LIKE '%diputado%' OR CONTENIDO LIKE '%senador%' OR CONTENIDO LIKE '%alcald%' OR
    CONTENIDO LIKE '%gobernador%' OR CONTENIDO LIKE '%campaña%' OR CONTENIDO LIKE '%INE%'
  );

-- Actualizar a ECONOMÍA
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'ECONOMIA'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%economía%' OR CONTENIDO LIKE '%dólar%' OR CONTENIDO LIKE '%peso%' OR
    CONTENIDO LIKE '%inflación%' OR CONTENIDO LIKE '%Banco%' OR CONTENIDO LIKE '%empresa%' OR
    CONTENIDO LIKE '%negocio%' OR CONTENIDO LIKE '%inversión%' OR CONTENIDO LIKE '%mercado%' OR
    CONTENIDO LIKE '%financiero%' OR CONTENIDO LIKE '%bolsa%' OR CONTENIDO LIKE '%Banxico%'
  );

-- Actualizar a DEPORTES
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'DEPORTES'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%fútbol%' OR CONTENIDO LIKE '%deporte%' OR CONTENIDO LIKE '%equipo%' OR
    CONTENIDO LIKE '%jugador%' OR CONTENIDO LIKE '%partido%' OR CONTENIDO LIKE '%gol%' OR
    CONTENIDO LIKE '%Mundial%' OR CONTENIDO LIKE '%olímpico%' OR CONTENIDO LIKE '%medalla%'
  );

-- Actualizar a CULTURA
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'CULTURA'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%cultura%' OR CONTENIDO LIKE '%arte%' OR CONTENIDO LIKE '%museo%' OR
    CONTENIDO LIKE '%exposición%' OR CONTENIDO LIKE '%artista%' OR CONTENIDO LIKE '%música%' OR
    CONTENIDO LIKE '%concierto%' OR CONTENIDO LIKE '%teatro%' OR CONTENIDO LIKE '%literatura%' OR
    CONTENIDO LIKE '%cine%' OR CONTENIDO LIKE '%película%' OR CONTENIDO LIKE '%festival%'
  );

-- Actualizar a TECNOLOGÍA
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'TECNOLOGIA'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%tecnología%' OR CONTENIDO LIKE '%digital%' OR CONTENIDO LIKE '%internet%' OR
    CONTENIDO LIKE '%app%' OR CONTENIDO LIKE '%plataforma%' OR CONTENIDO LIKE '%IA%' OR
    CONTENIDO LIKE '%inteligencia artificial%' OR CONTENIDO LIKE '%Google%' OR CONTENIDO LIKE '%Meta%' OR
    CONTENIDO LIKE '%WhatsApp%' OR CONTENIDO LIKE '%TikTok%' OR CONTENIDO LIKE '%redes sociales%'
  );

-- Actualizar a INTERNACIONAL
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'INTERNACIONAL'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%Estados Unidos%' OR CONTENIDO LIKE '%Trump%' OR CONTENIDO LIKE '%Europa%' OR
    CONTENIDO LIKE '%China%' OR CONTENIDO LIKE '%Irán%' OR CONTENIDO LIKE '%Rusia%' OR
    CONTENIDO LIKE '%guerra%' OR CONTENIDO LIKE '%conflicto%' OR CONTENIDO LIKE '%ONU%' OR
    CONTENIDO LIKE '%internacional%' OR CONTENIDO LIKE '%extranjero%'
  );

-- Actualizar a SUCESOS (notas rojas)
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'SUCESOS'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%asesinato%' OR CONTENIDO LIKE '%homicidio%' OR CONTENIDO LIKE '%muerte%' OR
    CONTENIDO LIKE '%violencia%' OR CONTENIDO LIKE '%crimen%' OR CONTENIDO LIKE '%delito%' OR
    CONTENIDO LIKE '%detenido%' OR CONTENIDO LIKE '%arrestado%' OR CONTENIDO LIKE '%FGR%' OR
    CONTENIDO LIKE '%fiscalía%' OR CONTENIDO LIKE '%cártel%' OR CONTENIDO LIKE '%narcotráfico%'
  );

-- Actualizar a SALUD
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'SALUD'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%salud%' OR CONTENIDO LIKE '%hospital%' OR CONTENIDO LIKE '%médico%' OR
    CONTENIDO LIKE '%enfermedad%' OR CONTENIDO LIKE '%vacuna%' OR CONTENIDO LIKE '%IMSS%' OR
    CONTENIDO LIKE '%ISSSTE%' OR CONTENIDO LIKE '%pandemia%' OR CONTENIDO LIKE '%epidemia%'
  );

-- Actualizar a EDUCACIÓN
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'EDUCACION'
WHERE ESTADO = 'PUBLICADO'
  AND (
    CONTENIDO LIKE '%educación%' OR CONTENIDO LIKE '%escuela%' OR CONTENIDO LIKE '%universidad%' OR
    CONTENIDO LIKE '%estudiante%' OR CONTENIDO LIKE '%maestro%' OR CONTENIDO LIKE '%alumno%' OR
    CONTENIDO LIKE '%SEP%' OR CONTENIDO LIKE '%beca%' OR CONTENIDO LIKE '%académico%'
  );

-- Actualizar restantes a NACIONAL (default)
UPDATE ARTICULOS_PARAFRASEADOS 
SET CATEGORIA = 'NACIONAL'
WHERE ESTADO = 'PUBLICADO' AND (CATEGORIA IS NULL OR CATEGORIA = 'NACIONAL');

-- ============================================================
-- 3. VERIFICACIÓN FINAL
-- ============================================================

-- Mostrar resumen de categorías
SELECT CATEGORIA, COUNT(*) as total
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO'
GROUP BY CATEGORIA
ORDER BY total DESC;

-- Mostrar duplicados restantes (debería ser 0)
SELECT SLUG, COUNT(*) as count
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO'
GROUP BY SLUG
HAVING count > 1;
