-- Migración simplificada - ejecutar por partes
-- Primero deshabilitar foreign keys
PRAGMA foreign_keys = OFF;

-- 1. RADIOCINCONOTICIAS
INSERT OR IGNORE INTO ARTICULOS_SITIO_RADIOCINCONOTICIAS (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-radio' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%radiocinconoticias%';

-- 2. CENTRALMEXICO
INSERT OR IGNORE INTO ARTICULOS_SITIO_CENTRALMEXICO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-central' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%centralmexico%';

-- 3. TVMEXICO
INSERT OR IGNORE INTO ARTICULOS_SITIO_TVMEXICO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-tv' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%tvmexico%';

-- 4. CBNNOTICIAS
INSERT OR IGNORE INTO ARTICULOS_SITIO_CBNNOTICIAS (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-cbn' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%cbnnoticias%';

-- 5. MEXICOINFORMADO
INSERT OR IGNORE INTO ARTICULOS_SITIO_MEXICOINFORMADO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-mexinfo' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%mexicoinformado%';

-- 6. NODOINFORMATIVO
INSERT OR IGNORE INTO ARTICULOS_SITIO_NODOINFORMATIVO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-nodo' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%nodoinformativo%';

-- 7. BITACORAURBANA
INSERT OR IGNORE INTO ARTICULOS_SITIO_BITACORAURBANA (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-bitacora' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%bitacoraurbana%';

-- 8. REPORTECENTRALMX
INSERT OR IGNORE INTO ARTICULOS_SITIO_REPORTECENTRALMX (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-reporte' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%reportecentralmx%';

-- 9. VERTICENOTICIAS
INSERT OR IGNORE INTO ARTICULOS_SITIO_VERTICENOTICIAS (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-vertice' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%verticenoticias%';

-- 10. NOTICIASOBJETIVO
INSERT OR IGNORE INTO ARTICULOS_SITIO_NOTICIASOBJETIVO (ID, ID_PARAFRASEADO, FECHA_ASIGNACION)
SELECT 
  'para-' || ID || '-objetivo' as ID,
  ID as ID_PARAFRASEADO,
  FECHA_PUBLICACION as FECHA_ASIGNACION
FROM ARTICULOS_PARAFRASEADOS
WHERE ESTADO = 'PUBLICADO' AND SITIO_DESTINO LIKE '%noticiasobjetivo%';

-- Verificación
SELECT 'PARAFRASEADOS migrados' as proceso, COUNT(*) as total
FROM (
  SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_RADIOCINCONOTICIAS
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_CENTRALMEXICO
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_TVMEXICO
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_CBNNOTICIAS
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_MEXICOINFORMADO
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_NODOINFORMATIVO
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_BITACORAURBANA
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_REPORTECENTRALMX
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_VERTICENOTICIAS
  UNION ALL SELECT ID_PARAFRASEADO FROM ARTICULOS_SITIO_NOTICIASOBJETIVO
);
