-- Migración: Eliminar columnas WEB_FECHA, WEB_URL y WEB_PUBLICADO de todas las tablas ARTICULOS_SITIO_*
-- SQLite no soporta DROP COLUMN directamente, hay que recrear las tablas
-- Ejecutar: wrangler d1 execute news_db --file migrate_remove_web_columns.sql --remote
-- Fecha: 2026-03-11

-- ============================================================
-- SITIOS ESTABLES (10)
-- ============================================================

-- 1. Radio Cinco Noticias
DROP TABLE IF EXISTS ARTICULOS_SITIO_RADIOCINCONOTICIAS_BACKUP;
ALTER TABLE ARTICULOS_SITIO_RADIOCINCONOTICIAS RENAME TO ARTICULOS_SITIO_RADIOCINCONOTICIAS_BACKUP;
CREATE TABLE ARTICULOS_SITIO_RADIOCINCONOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_RADIOCINCONOTICIAS (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_RADIOCINCONOTICIAS_BACKUP;
DROP TABLE ARTICULOS_SITIO_RADIOCINCONOTICIAS_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_radiocinconoticias_fb ON ARTICULOS_SITIO_RADIOCINCONOTICIAS(FB_PUBLICADO);

-- 2. Central México
DROP TABLE IF EXISTS ARTICULOS_SITIO_CENTRALMEXICO_BACKUP;
ALTER TABLE ARTICULOS_SITIO_CENTRALMEXICO RENAME TO ARTICULOS_SITIO_CENTRALMEXICO_BACKUP;
CREATE TABLE ARTICULOS_SITIO_CENTRALMEXICO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_CENTRALMEXICO (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_CENTRALMEXICO_BACKUP;
DROP TABLE ARTICULOS_SITIO_CENTRALMEXICO_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_centralmexico_fb ON ARTICULOS_SITIO_CENTRALMEXICO(FB_PUBLICADO);

-- 3. TV México
DROP TABLE IF EXISTS ARTICULOS_SITIO_TVMEXICO_BACKUP;
ALTER TABLE ARTICULOS_SITIO_TVMEXICO RENAME TO ARTICULOS_SITIO_TVMEXICO_BACKUP;
CREATE TABLE ARTICULOS_SITIO_TVMEXICO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_TVMEXICO (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_TVMEXICO_BACKUP;
DROP TABLE ARTICULOS_SITIO_TVMEXICO_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_tvmexico_fb ON ARTICULOS_SITIO_TVMEXICO(FB_PUBLICADO);

-- 4. CBN Noticias
DROP TABLE IF EXISTS ARTICULOS_SITIO_CBNNOTICIAS_BACKUP;
ALTER TABLE ARTICULOS_SITIO_CBNNOTICIAS RENAME TO ARTICULOS_SITIO_CBNNOTICIAS_BACKUP;
CREATE TABLE ARTICULOS_SITIO_CBNNOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_CBNNOTICIAS (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_CBNNOTICIAS_BACKUP;
DROP TABLE ARTICULOS_SITIO_CBNNOTICIAS_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_cbnnoticias_fb ON ARTICULOS_SITIO_CBNNOTICIAS(FB_PUBLICADO);

-- 5. México Informado
DROP TABLE IF EXISTS ARTICULOS_SITIO_MEXICOINFORMADO_BACKUP;
ALTER TABLE ARTICULOS_SITIO_MEXICOINFORMADO RENAME TO ARTICULOS_SITIO_MEXICOINFORMADO_BACKUP;
CREATE TABLE ARTICULOS_SITIO_MEXICOINFORMADO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_MEXICOINFORMADO (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_MEXICOINFORMADO_BACKUP;
DROP TABLE ARTICULOS_SITIO_MEXICOINFORMADO_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_mexicoinformado_fb ON ARTICULOS_SITIO_MEXICOINFORMADO(FB_PUBLICADO);

-- 6. Nodo Informativo
DROP TABLE IF EXISTS ARTICULOS_SITIO_NODOINFORMATIVO_BACKUP;
ALTER TABLE ARTICULOS_SITIO_NODOINFORMATIVO RENAME TO ARTICULOS_SITIO_NODOINFORMATIVO_BACKUP;
CREATE TABLE ARTICULOS_SITIO_NODOINFORMATIVO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_NODOINFORMATIVO (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_NODOINFORMATIVO_BACKUP;
DROP TABLE ARTICULOS_SITIO_NODOINFORMATIVO_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_nodoinformativo_fb ON ARTICULOS_SITIO_NODOINFORMATIVO(FB_PUBLICADO);

-- 7. Bitácora Urbana
DROP TABLE IF EXISTS ARTICULOS_SITIO_BITACORAURBANA_BACKUP;
ALTER TABLE ARTICULOS_SITIO_BITACORAURBANA RENAME TO ARTICULOS_SITIO_BITACORAURBANA_BACKUP;
CREATE TABLE ARTICULOS_SITIO_BITACORAURBANA (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_BITACORAURBANA (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_BITACORAURBANA_BACKUP;
DROP TABLE ARTICULOS_SITIO_BITACORAURBANA_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_bitacoraurbana_fb ON ARTICULOS_SITIO_BITACORAURBANA(FB_PUBLICADO);

-- 8. Reporte Central MX
DROP TABLE IF EXISTS ARTICULOS_SITIO_REPORTECENTRALMX_BACKUP;
ALTER TABLE ARTICULOS_SITIO_REPORTECENTRALMX RENAME TO ARTICULOS_SITIO_REPORTECENTRALMX_BACKUP;
CREATE TABLE ARTICULOS_SITIO_REPORTECENTRALMX (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_REPORTECENTRALMX (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_REPORTECENTRALMX_BACKUP;
DROP TABLE ARTICULOS_SITIO_REPORTECENTRALMX_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_reportecentralmx_fb ON ARTICULOS_SITIO_REPORTECENTRALMX(FB_PUBLICADO);

-- 9. Vértice Noticias
DROP TABLE IF EXISTS ARTICULOS_SITIO_VERTICENOTICIAS_BACKUP;
ALTER TABLE ARTICULOS_SITIO_VERTICENOTICIAS RENAME TO ARTICULOS_SITIO_VERTICENOTICIAS_BACKUP;
CREATE TABLE ARTICULOS_SITIO_VERTICENOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_VERTICENOTICIAS (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_VERTICENOTICIAS_BACKUP;
DROP TABLE ARTICULOS_SITIO_VERTICENOTICIAS_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_verticenoticias_fb ON ARTICULOS_SITIO_VERTICENOTICIAS(FB_PUBLICADO);

-- 10. Noticias Objetivo
DROP TABLE IF EXISTS ARTICULOS_SITIO_NOTICIASOBJETIVO_BACKUP;
ALTER TABLE ARTICULOS_SITIO_NOTICIASOBJETIVO RENAME TO ARTICULOS_SITIO_NOTICIASOBJETIVO_BACKUP;
CREATE TABLE ARTICULOS_SITIO_NOTICIASOBJETIVO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
INSERT INTO ARTICULOS_SITIO_NOTICIASOBJETIVO (ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION)
SELECT ID, ID_PARAFRASEADO, FB_PUBLICADO, FB_FECHA, FB_POST_ID, FECHA_ASIGNACION, FECHA_CREACION FROM ARTICULOS_SITIO_NOTICIASOBJETIVO_BACKUP;
DROP TABLE ARTICULOS_SITIO_NOTICIASOBJETIVO_BACKUP;
CREATE INDEX IF NOT EXISTS idx_sitio_noticiasobjetivo_fb ON ARTICULOS_SITIO_NOTICIASOBJETIVO(FB_PUBLICADO);

-- ============================================================
-- NOTA: Para los 17 nuevos sitios, ejecutar solo si las tablas existen
-- Las nuevas tablas ya se crean sin WEB_FECHA, WEB_URL y WEB_PUBLICADO
-- ============================================================
