-- Tabla de Cola para Facebook Publishing
-- Cada sitio tiene su propia cola independiente

CREATE TABLE IF NOT EXISTS FACEBOOK_QUEUE (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  SLUG_SITIO TEXT NOT NULL,
  
  -- Estado de la cola
  ESTADO TEXT DEFAULT 'PENDIENTE',  -- PENDIENTE, EN_PROCESO, PUBLICADO, FALLIDO
  
  -- Reintentos
  INTENTOS INTEGER DEFAULT 0,
  MAX_INTENTOS INTEGER DEFAULT 3,
  
  -- Timestamps
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FECHA_PROGRAMADA TEXT,  -- Cuándo se debe publicar
  FECHA_PROCESO TEXT,     -- Cuándo se empezó a procesar
  FECHA_PUBLICADO TEXT,   -- Cuándo se publicó
  
  -- Resultado
  FB_POST_ID TEXT,
  FB_ERROR TEXT,
  
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);

CREATE INDEX IF NOT EXISTS idx_fb_queue_estado ON FACEBOOK_QUEUE(ESTADO);
CREATE INDEX IF NOT EXISTS idx_fb_queue_sitio ON FACEBOOK_QUEUE(SLUG_SITIO);
CREATE INDEX IF NOT EXISTS idx_fb_queue_programada ON FACEBOOK_QUEUE(FECHA_PROGRAMADA);

-- Insertar artículos existentes pendientes en la cola
INSERT INTO FACEBOOK_QUEUE (ID, ID_PARAFRASEADO, SLUG_SITIO, ESTADO, FECHA_PROGRAMADA)
SELECT 
  'queue-' || s.ID,
  s.ID_PARAFRASEADO,
  REPLACE(REPLACE(s.TABLE_NAME, 'ARTICULOS_SITIO_', ''), '_', '-') as SLUG_SITIO,
  'PENDIENTE',
  datetime('now')
FROM (
  SELECT 'ARTICULOS_SITIO_RADIOCINCONOTICIAS' as TABLE_NAME, ID_PARAFRASEADO FROM ARTICULOS_SITIO_RADIOCINCONOTICIAS WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_CENTRALMEXICO', ID_PARAFRASEADO FROM ARTICULOS_SITIO_CENTRALMEXICO WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_TVMEXICO', ID_PARAFRASEADO FROM ARTICULOS_SITIO_TVMEXICO WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_CBNNOTICIAS', ID_PARAFRASEADO FROM ARTICULOS_SITIO_CBNNOTICIAS WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_MEXICOINFORMADO', ID_PARAFRASEADO FROM ARTICULOS_SITIO_MEXICOINFORMADO WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_NODOINFORMATIVO', ID_PARAFRASEADO FROM ARTICULOS_SITIO_NODOINFORMATIVO WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_BITACORAURBANA', ID_PARAFRASEADO FROM ARTICULOS_SITIO_BITACORAURBANA WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_REPORTECENTRALMX', ID_PARAFRASEADO FROM ARTICULOS_SITIO_REPORTECENTRALMX WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_VERTICENOTICIAS', ID_PARAFRASEADO FROM ARTICULOS_SITIO_VERTICENOTICIAS WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
  UNION ALL SELECT 'ARTICULOS_SITIO_NOTICIASOBJETIVO', ID_PARAFRASEADO FROM ARTICULOS_SITIO_NOTICIASOBJETIVO WHERE WEB_PUBLICADO = 1 AND FB_PUBLICADO = 0
) s
WHERE NOT EXISTS (
  SELECT 1 FROM FACEBOOK_QUEUE fq WHERE fq.ID_PARAFRASEADO = s.ID_PARAFRASEADO
);
