-- Schema para 27 tablas ARTICULOS_SITIO_{SLUG}
-- Cada tabla rastrea el estado individual de artículos por sitio
-- Actualizado: 2026-03-11
-- Nota: WEB_FECHA, WEB_URL y WEB_PUBLICADO eliminadas - todos los artículos en estas tablas están publicados
-- La fecha y URL se obtienen dinámicamente de ARTICULOS_PARAFRASEADOS

-- ============================================================
-- SITIOS ESTABLES (10)
-- ============================================================

-- 1. Radio Cinco Noticias
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_RADIOCINCONOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_radiocinconoticias_fb ON ARTICULOS_SITIO_RADIOCINCONOTICIAS(FB_PUBLICADO);

-- 2. Central México
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_CENTRALMEXICO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_centralmexico_fb ON ARTICULOS_SITIO_CENTRALMEXICO(FB_PUBLICADO);

-- 3. TV México
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_TVMEXICO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_tvmexico_fb ON ARTICULOS_SITIO_TVMEXICO(FB_PUBLICADO);

-- 4. CBN Noticias
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_CBNNOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_cbnnoticias_fb ON ARTICULOS_SITIO_CBNNOTICIAS(FB_PUBLICADO);

-- 5. México Informado
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_MEXICOINFORMADO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_mexicoinformado_fb ON ARTICULOS_SITIO_MEXICOINFORMADO(FB_PUBLICADO);

-- 6. Nodo Informativo
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_NODOINFORMATIVO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_nodoinformativo_fb ON ARTICULOS_SITIO_NODOINFORMATIVO(FB_PUBLICADO);

-- 7. Bitácora Urbana
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_BITACORAURBANA (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_bitacoraurbana_fb ON ARTICULOS_SITIO_BITACORAURBANA(FB_PUBLICADO);

-- 8. Reporte Central MX
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_REPORTECENTRALMX (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_reportecentralmx_fb ON ARTICULOS_SITIO_REPORTECENTRALMX(FB_PUBLICADO);

-- 9. Vértice Noticias
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_VERTICENOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_verticenoticias_fb ON ARTICULOS_SITIO_VERTICENOTICIAS(FB_PUBLICADO);

-- 10. Noticias Objetivo
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_NOTICIASOBJETIVO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_noticiasobjetivo_fb ON ARTICULOS_SITIO_NOTICIASOBJETIVO(FB_PUBLICADO);

-- ============================================================
-- NUEVOS SITIOS (17)
-- ============================================================

-- 11. Boominformativo
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_BOOMINFORMATIVO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_boominformativo_fb ON ARTICULOS_SITIO_BOOMINFORMATIVO(FB_PUBLICADO);

-- 12. Capital Press
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_CAPITALPRESS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_capitalpress_fb ON ARTICULOS_SITIO_CAPITALPRESS(FB_PUBLICADO);

-- 13. Diario Express
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_DIARIOEXPRESS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_diarioexpress_fb ON ARTICULOS_SITIO_DIARIOEXPRESS(FB_PUBLICADO);

-- 14. El Pulso Mexicano
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_ELPULSOMEXICANO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_elpulsomexicano_fb ON ARTICULOS_SITIO_ELPULSOMEXICANO(FB_PUBLICADO);

-- 15. Enfoque Capital
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_ENFOQUECAPITAL (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_enfoquecapital_fb ON ARTICULOS_SITIO_ENFOQUECAPITAL(FB_PUBLICADO);

-- 16. Enfoque Directo
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_ENFOQUEDIRECTO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_enfoquedirecto_fb ON ARTICULOS_SITIO_ENFOQUEDIRECTO(FB_PUBLICADO);

-- 17. Fórmula CDMX
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_FORMULACDMX (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_formulacdmx_fb ON ARTICULOS_SITIO_FORMULACDMX(FB_PUBLICADO);

-- 18. The Mexican Times
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_MEXICANTIMES (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_mexicantimes_fb ON ARTICULOS_SITIO_MEXICANTIMES(FB_PUBLICADO);

-- 19. México 360 Noticias
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_MEXICO360NOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_mexico360noticias_fb ON ARTICULOS_SITIO_MEXICO360NOTICIAS(FB_PUBLICADO);

-- 20. M Radio
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_MRADIO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_mradio_fb ON ARTICULOS_SITIO_MRADIO(FB_PUBLICADO);

-- 21. Noticias Horizonte
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_NOTICIASHORIZONTE (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_noticiashorizonte_fb ON ARTICULOS_SITIO_NOTICIASHORIZONTE(FB_PUBLICADO);

-- 22. Pulso Diario
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_PULSODIARIO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_pulsodiario_fb ON ARTICULOS_SITIO_PULSODIARIO(FB_PUBLICADO);

-- 23. Punto Clave
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_PUNTOCLAVE (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_puntoclave_fb ON ARTICULOS_SITIO_PUNTOCLAVE(FB_PUBLICADO);

-- 24. Punto Noticias
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_PUNTONOTICIAS (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_puntonoticias_fb ON ARTICULOS_SITIO_PUNTONOTICIAS(FB_PUBLICADO);

-- 25. Radar Informativo
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_RADARINFORMATIVO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_radarinformativo_fb ON ARTICULOS_SITIO_RADARINFORMATIVO(FB_PUBLICADO);

-- 26. Reporte Diario
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_REPORTEDIARIO (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_reportediario_fb ON ARTICULOS_SITIO_REPORTEDIARIO(FB_PUBLICADO);

-- 27. Televisión ABC
CREATE TABLE IF NOT EXISTS ARTICULOS_SITIO_TELEVISIONABC (
  ID TEXT PRIMARY KEY,
  ID_PARAFRASEADO TEXT NOT NULL,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_POST_ID TEXT,
  FECHA_ASIGNACION TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (ID_PARAFRASEADO) REFERENCES ARTICULOS_PARAFRASEADOS(ID)
);
CREATE INDEX IF NOT EXISTS idx_sitio_televisionabc_fb ON ARTICULOS_SITIO_TELEVISIONABC(FB_PUBLICADO);
