-- D1 schema for Cloudflare News API
-- Actualizado: Febrero 2026 - Tablas innecesarias eliminadas

-- ============================================================
-- TABLAS PRINCIPALES - Flujo de Noticias
-- ============================================================

-- Tabla de Artículos Originales (Fuente)
CREATE TABLE IF NOT EXISTS ARTICULOS_ORIGINALES (
  ID TEXT PRIMARY KEY,
  URL TEXT NOT NULL,
  TITULO TEXT NOT NULL,
  DESCRIPCION TEXT,
  URL_IMAGEN TEXT,
  URL_IMAGEN2 TEXT,
  FECHA TEXT,
  CONTENIDO TEXT,
  CATEGORIA TEXT,
  LONGITUD INTEGER,
  SITIOS INTEGER DEFAULT 0
);

-- Tabla de Artículos Parafraseados (Destino)
CREATE TABLE IF NOT EXISTS ARTICULOS_PARAFRASEADOS (
  ID TEXT PRIMARY KEY,
  ID_ARTICULO_ORIGINAL TEXT,
  TITULO_PARAFRASEADO TEXT NOT NULL,
  DESCRIPCION_PARAFRASEADA TEXT,
  CONTENIDO TEXT,
  LONGITUD INTEGER,
  SITIO_DESTINO TEXT,
  CATEGORIA TEXT,
  FECHA_PUBLICACION TEXT,
  AUTOR TEXT,
  VERIFICACION TEXT,
  DESTACADO INTEGER DEFAULT 0,
  URL_IMAGEN TEXT,
  SLUG TEXT,
  VISTAS INTEGER DEFAULT 0,
  ESTADO TEXT DEFAULT 'PUBLICADO',
  FB_REQUERIDO INTEGER DEFAULT 0,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_SITIOS_PUBLICADOS TEXT DEFAULT '',
  ES_BREVE INTEGER DEFAULT 0,
  SOURCE_URL TEXT,
  FOREIGN KEY (ID_ARTICULO_ORIGINAL) REFERENCES ARTICULOS_ORIGINALES(ID)
);

-- Artículos redactados directamente en el CMS (Contenido Original Interno)
CREATE TABLE IF NOT EXISTS ARTICULOS_CMS (
  ID TEXT PRIMARY KEY,
  TITULO TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  DESCRIPCION TEXT,
  CONTENIDO TEXT,
  CATEGORIA TEXT,
  ID_AUTOR INTEGER,
  URL_IMAGEN TEXT,
  SITIOS_DESTINO TEXT,
  ESTADO TEXT DEFAULT 'BORRADOR',
  DESTACADO INTEGER DEFAULT 0,
  FECHA_CREACION TEXT DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION TEXT,
  FB_PUBLICADO INTEGER DEFAULT 0,
  FB_FECHA TEXT,
  FB_REQUERIDO INTEGER DEFAULT 0,
  FB_SITIOS_PUBLICADOS TEXT DEFAULT '',
  FOREIGN KEY (ID_AUTOR) REFERENCES USUARIOS(ID)
);

-- ============================================================
-- GESTIÓN DE SITIOS
-- ============================================================

CREATE TABLE IF NOT EXISTS SITIOS (
  ID TEXT PRIMARY KEY,
  SLUG TEXT NOT NULL UNIQUE,
  NOMBRE TEXT NOT NULL,
  DOMINIO TEXT NOT NULL UNIQUE,
  TAGLINE TEXT,
  LOGO_URL TEXT,
  FAVICON_URL TEXT,
  TEMPLATE_ID INTEGER DEFAULT 1,
  ACTIVO INTEGER DEFAULT 1,
  FACEBOOK_ACTIVO INTEGER DEFAULT 1,
  FACEBOOK_PAGE_ID TEXT,
  FACEBOOK_TOKEN_SECRET TEXT
);

-- Textos legales por sitio
CREATE TABLE IF NOT EXISTS LEGALES (
  ID_SITIO TEXT PRIMARY KEY,
  TERMINOS_CONDICIONES TEXT,
  POLITICA_PRIVACIDAD TEXT,
  POLITICA_COOKIES TEXT,
  ACERCA_DE TEXT,
  CONTACTO_EMAIL TEXT,
  CONTACTO_TELEFONO TEXT,
  CONTACTO_DIRECCION TEXT,
  ULTIMA_ACTUALIZACION TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_SITIO) REFERENCES SITIOS(ID)
);

-- Canales Externos y Redes Sociales por Sitio
CREATE TABLE IF NOT EXISTS CANALES_EXTERNOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_SITIO TEXT,
  TIPO TEXT NOT NULL,
  URL TEXT NOT NULL,
  ETIQUETA TEXT,
  ICONO_CLASE TEXT,
  ORDEN INTEGER DEFAULT 0,
  ACTIVO INTEGER DEFAULT 1,
  FOREIGN KEY (ID_SITIO) REFERENCES SITIOS(ID)
);

-- Menús de Navegación Dinámicos por Sitio
CREATE TABLE IF NOT EXISTS MENUS_NAVEGACION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_SITIO TEXT,
  ETIQUETA TEXT NOT NULL,
  URL TEXT NOT NULL,
  POSICION TEXT DEFAULT 'HEADER',
  ORDEN INTEGER DEFAULT 0,
  ACTIVO INTEGER DEFAULT 1,
  FOREIGN KEY (ID_SITIO) REFERENCES SITIOS(ID)
);

-- ============================================================
-- MESA DE REVISIÓN Y FLUJO DE TRABAJO
-- ============================================================

-- Mesa de Revisión: Buffer antes de la publicación final
CREATE TABLE IF NOT EXISTS REVISION_CONTENIDO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_ORIGEN TEXT NOT NULL,
  TIPO_ORIGEN TEXT NOT NULL,
  TITULO_PROPUESTO TEXT,
  CONTENIDO_PROPUESTO TEXT,
  DESCRIPCION_PROPUESTA TEXT,
  SITIO_DESTINO TEXT,
  CATEGORIA TEXT,
  ESTADO TEXT DEFAULT 'PENDIENTE',
  NOTAS_REVISOR TEXT,
  FECHA_PARA_PUBLICAR TEXT,
  FECHA_CREACION TEXT DEFAULT CURRENT_TIMESTAMP,
  URL_IMAGEN TEXT,
  FB_REQUERIDO INTEGER DEFAULT 0,
  ES_BREVE INTEGER DEFAULT 0
);

-- ============================================================
-- CATEGORÍAS Y USUARIOS
-- ============================================================

-- Categorías Maestras
CREATE TABLE IF NOT EXISTS CATEGORIAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  ACTIVA INTEGER DEFAULT 1
);

-- Usuarios del Sistema (Admin/Editores)
CREATE TABLE IF NOT EXISTS USUARIOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE TEXT NOT NULL,
  EMAIL TEXT NOT NULL UNIQUE,
  ROL TEXT DEFAULT 'editor',
  ACTIVO INTEGER DEFAULT 1
);

-- ============================================================
-- TICKER EN VIVO
-- ============================================================

-- Datos financieros para el ticker (USD, EUR, BTC, Oro, Petróleo, IPC)
CREATE TABLE IF NOT EXISTS TICKER_FINANCIALS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SIMBOLO TEXT NOT NULL UNIQUE,
  NOMBRE TEXT NOT NULL,
  VALOR TEXT NOT NULL,
  CAMBIO TEXT DEFAULT '0.00%',
  TENDENCIA TEXT DEFAULT 'up',
  UNIDAD TEXT DEFAULT 'MXN',
  FECHA_ACTUALIZACION TEXT DEFAULT (datetime('now'))
);

-- Titulares de noticias para el ticker de breaking news
CREATE TABLE IF NOT EXISTS TICKER_HEADLINES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TITULO TEXT NOT NULL,
  URL TEXT,
  FUENTE TEXT,
  FECHA_CREACION TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ticker_headlines_fecha ON TICKER_HEADLINES(FECHA_CREACION DESC);

-- ============================================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_art_orig_url ON ARTICULOS_ORIGINALES(URL);
CREATE INDEX IF NOT EXISTS idx_art_para_sitio ON ARTICULOS_PARAFRASEADOS(SITIO_DESTINO);
CREATE INDEX IF NOT EXISTS idx_art_para_fecha ON ARTICULOS_PARAFRASEADOS(FECHA_PUBLICACION DESC);
CREATE INDEX IF NOT EXISTS idx_art_cms_estado ON ARTICULOS_CMS(ESTADO);
CREATE INDEX IF NOT EXISTS idx_revision_estado ON REVISION_CONTENIDO(ESTADO);
CREATE INDEX IF NOT EXISTS idx_canales_sitio ON CANALES_EXTERNOS(ID_SITIO);
CREATE INDEX IF NOT EXISTS idx_menus_sitio ON MENUS_NAVEGACION(ID_SITIO);
