-- Seed data for ARTICULOS_ORIGINALES and ARTICULOS_PARAFRASEADOS
-- Generated by seed_db.py

-- Add URL_IMAGEN column if not exists (safe to run multiple times)
ALTER TABLE ARTICULOS_PARAFRASEADOS ADD COLUMN URL_IMAGEN TEXT;

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.elfinanciero.com.mx/cdmx/2026/02/18/clara-brugada-encabeza-primer-simulacro-metropolitano-cdmx-y-edomex-coordinan-respuesta-ante-sismo/', 'https://www.elfinanciero.com.mx/cdmx/2026/02/18/clara-brugada-encabeza-primer-simulacro-metropolitano-cdmx-y-edomex-coordinan-respuesta-ante-sismo/', 'Clara Brugada encabeza primer simulacro metropolitano; CDMX y Edomex coordinan respuesta ante sismo', 'El ejercicio integra de manera inédita el sistema de alerta sísmica directamente en dispositivos móviles, complementando la red de altavoces en lo que representa el primero de tres simulacros programados para este año.

La Jefa de Gobierno, Clara Brugada Molina, supervisó el inicio del Primer Simula...', 'https://www.elfinanciero.com.mx/resizer/v2/JMKOGP6KPNBC3K7OHTWCRMYT64.jpeg?smart=true&auth=53fc65491ff88b0619d2fe04f388f938906daa4ddfb5d3edda38ca40fa3f5cc2&width=1200&height=630', '2026-02-18T23:56:33Z', 'El ejercicio integra de manera inédita el sistema de alerta sísmica directamente en dispositivos móviles, complementando la red de altavoces en lo que representa el primero de tres simulacros programados para este año.

La Jefa de Gobierno, Clara Brugada Molina, supervisó el inicio del Primer Simulacro Metropolitano 2026 , un ejercicio preventivo de gran escala que, por primera ocasión, coordina esfuerzos institucionales entre la Ciudad de México y el Estado de México para reforzar la respuesta ante fenómenos naturales que no respetan fronteras administrativas.

En punto de las 11:00 horas se activó la alerta sísmica en los altavoces de la capital y, de forma simultánea, en los dispositivos móviles de la ciudadanía. Bajo una hipótesis de sismo magnitud 7.2 con epicentro en el estado de Oaxaca, el gobierno capitalino dio inicio a los protocolos de emergencia a través de la Secretaría de Gestión Integral de Riesgos y Protección Civil, el Heroico Cuerpo de Bomberos y el Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano (C5).

El Secretario de Seguridad Ciudadana, Pablo Vázquez Camacho, informó que tras la activación de la alerta se desplegó el protocolo de seguridad correspondiente', 'Política'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.elfinanciero.com.mx/cdmx/2026/02/18/clara-brugada-encabeza-primer-simulacro-metropolitano-cdmx-y-edomex-coordinan-respuesta-ante-sismo/', 'Clara Brugada encabeza primer simulacro metropolitano; CDMX y Edomex coordinan respuesta ante sismo', 'El ejercicio integra de manera inédita el sistema de alerta sísmica directamente en dispositivos móviles, complementando la red de altavoces en lo que representa el primero de tres simulacros programados para este año.

La Jefa de Gobierno, Clara Brugada Molina, supervisó el inicio del Primer Simula...', 'El ejercicio integra de manera inédita el sistema de alerta sísmica directamente en dispositivos móviles, complementando la red de altavoces en lo que representa el primero de tres simulacros programados para este año.

La Jefa de Gobierno, Clara Brugada Molina, supervisó el inicio del Primer Simulacro Metropolitano 2026 , un ejercicio preventivo de gran escala que, por primera ocasión, coordina esfuerzos institucionales entre la Ciudad de México y el Estado de México para reforzar la respuesta ante fenómenos naturales que no respetan fronteras administrativas.

En punto de las 11:00 horas se activó la alerta sísmica en los altavoces de la capital y, de forma simultánea, en los dispositivos móviles de la ciudadanía. Bajo una hipótesis de sismo magnitud 7.2 con epicentro en el estado de Oaxaca, el gobierno capitalino dio inicio a los protocolos de emergencia a través de la Secretaría de Gestión Integral de Riesgos y Protección Civil, el Heroico Cuerpo de Bomberos y el Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano (C5).

El Secretario de Seguridad Ciudadana, Pablo Vázquez Camacho, informó que tras la activación de la alerta se desplegó el protocolo de seguridad correspondiente', 1220, 'bitacoraurbana', 'Política', '2026-02-18T23:56:33Z', 'Redacción', 1, 'https://www.elfinanciero.com.mx/resizer/v2/JMKOGP6KPNBC3K7OHTWCRMYT64.jpeg?smart=true&auth=53fc65491ff88b0619d2fe04f388f938906daa4ddfb5d3edda38ca40fa3f5cc2&width=1200&height=630'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://es.cointelegraph.com/news/espana-es-la-segunda-plataforma-global-para-la-expansion-de-empresas-latinoamericanas-segun-estudio-de-ceapi', 'https://es.cointelegraph.com/news/espana-es-la-segunda-plataforma-global-para-la-expansion-de-empresas-latinoamericanas-segun-estudio-de-ceapi', 'España es la segunda plataforma global para la expansión de empresas latinoamericanas, según estudio', 'España se posiciona como la segunda plataforma global para la expansión de empresas latinoamericanas, según un estudio basado en el análisis de 54 millones de datos empresariales.España está reforzando su papel como nodo estratégico en la internacionalización…

España se posiciona como la segunda pl...', 'https://images.cointelegraph.com/cdn-cgi/image/f=auto,onerror=redirect,w=1200/https://s3.cointelegraph.com/uploads/2026-02/019c732d-8ca1-7982-9fe6-0cc5e16b571a.jpg', '2026-02-18T23:56:09Z', 'España se posiciona como la segunda plataforma global para la expansión de empresas latinoamericanas, según un estudio basado en el análisis de 54 millones de datos empresariales.España está reforzando su papel como nodo estratégico en la internacionalización…

España se posiciona como la segunda plataforma global para la expansión de empresas latinoamericanas, según un estudio basado en el análisis de 54 millones de datos empresariales.

España está reforzando su papel como nodo estratégico en la internacionalización de empresas latinoamericanas . Así lo planteó el estudio “España, el trampolín de las empresas latinoamericanas en el mundo”, presentado por el Consejo Empresarial Alianza por Iberoamérica (CEAPI) junto a un equipo del Instituto Complutense de Estudios Internacionales (ICEI), que analiza en profundidad cómo las compañías de la región estructuran su expansión global a través de filiales en terceros países.

Durante la presentación, realizada a través de una plataforma de videollamadas y donde estuvo presente Cointelegraph en Español, la presidenta de CEAPI, Núria Vilanova, explicó que el informe examina el denominado “efecto trampolín”, un mecanismo mediante el cual las empresas establecen estructuras corporativas en un país inte', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://es.cointelegraph.com/news/espana-es-la-segunda-plataforma-global-para-la-expansion-de-empresas-latinoamericanas-segun-estudio-de-ceapi', 'España es la segunda plataforma global para la expansión de empresas latinoamericanas, según estudio', 'España se posiciona como la segunda plataforma global para la expansión de empresas latinoamericanas, según un estudio basado en el análisis de 54 millones de datos empresariales.España está reforzando su papel como nodo estratégico en la internacionalización…

España se posiciona como la segunda pl...', 'España se posiciona como la segunda plataforma global para la expansión de empresas latinoamericanas, según un estudio basado en el análisis de 54 millones de datos empresariales.España está reforzando su papel como nodo estratégico en la internacionalización…

España se posiciona como la segunda plataforma global para la expansión de empresas latinoamericanas, según un estudio basado en el análisis de 54 millones de datos empresariales.

España está reforzando su papel como nodo estratégico en la internacionalización de empresas latinoamericanas . Así lo planteó el estudio “España, el trampolín de las empresas latinoamericanas en el mundo”, presentado por el Consejo Empresarial Alianza por Iberoamérica (CEAPI) junto a un equipo del Instituto Complutense de Estudios Internacionales (ICEI), que analiza en profundidad cómo las compañías de la región estructuran su expansión global a través de filiales en terceros países.

Durante la presentación, realizada a través de una plataforma de videollamadas y donde estuvo presente Cointelegraph en Español, la presidenta de CEAPI, Núria Vilanova, explicó que el informe examina el denominado “efecto trampolín”, un mecanismo mediante el cual las empresas establecen estructuras corporativas en un país inte', 1262, 'cbnnoticias', 'Tecnología', '2026-02-18T23:56:09Z', 'Kevin Rivera', 1, 'https://images.cointelegraph.com/cdn-cgi/image/f=auto,onerror=redirect,w=1200/https://s3.cointelegraph.com/uploads/2026-02/019c732d-8ca1-7982-9fe6-0cc5e16b571a.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.elfinanciero.com.mx/cdmx/2026/02/18/una-vez-mas-cdmx-y-edomex-la-libran-hoy-no-circula-del-jueves-19-de-febrero/', 'https://www.elfinanciero.com.mx/cdmx/2026/02/18/una-vez-mas-cdmx-y-edomex-la-libran-hoy-no-circula-del-jueves-19-de-febrero/', 'Una vez más, CDMX y Edomex ‘la libran’: Hoy No Circula del jueves 19 de febrero', 'El Hoy no Circula para la CDMX y el Edomex entra en vigor a las 5:00 y termina a las 22:00 horas; tiene como objetivo disminuir la contaminación del aire.

Luego de que la Ciudad de México tuviera varios días de Doble Hoy No Circula , todo vuelve a la normalidad, aunque se reportó mala calidad del a...', 'https://www.elfinanciero.com.mx/resizer/v2/I7SZUWS4ZZEYTH7TJ3KYND2BUI.jpeg?smart=true&auth=8fe12fe9a260fc27e29a669cddaff102ddbcd9b3fbb55d9065bee22c4d8873fc&width=1200&height=630', '2026-02-18T23:52:16Z', 'El Hoy no Circula para la CDMX y el Edomex entra en vigor a las 5:00 y termina a las 22:00 horas; tiene como objetivo disminuir la contaminación del aire.

Luego de que la Ciudad de México tuviera varios días de Doble Hoy No Circula , todo vuelve a la normalidad, aunque se reportó mala calidad del aire el miércoles 18 de febrero .

Al corte de las 17:00 horas de este miércoles 18 de febrero , las autoridades medioambientales reportaron mala calidad del aire , con presencia de partículas de ozono .

No se ha determinado que para el jueves 19 de febrero haya un Doble Hoy No Circula por contingencia ambiental, por lo que el programa operará con normalidad.

Además, considera si a diario usas el Metro de la Ciudad de México , considera que la Línea 2 estará en obras, por lo que habrá servicio de RTP para varias estaciones.

En las 16 alcaldías de la CDMX y en los 18 municipios colindantes del Estado de México te pueden multar si no respetas el Hoy No Circula .

La restricción vehicular, que entra en vigor a las 5:00 y termina a las 22:00 horas, tiene como objetivo disminuir la contaminación del aire y mejorar la calidad ambiental en la Zona M', 'Nacional'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.elfinanciero.com.mx/cdmx/2026/02/18/una-vez-mas-cdmx-y-edomex-la-libran-hoy-no-circula-del-jueves-19-de-febrero/', 'Una vez más, CDMX y Edomex ‘la libran’: Hoy No Circula del jueves 19 de febrero', 'El Hoy no Circula para la CDMX y el Edomex entra en vigor a las 5:00 y termina a las 22:00 horas; tiene como objetivo disminuir la contaminación del aire.

Luego de que la Ciudad de México tuviera varios días de Doble Hoy No Circula , todo vuelve a la normalidad, aunque se reportó mala calidad del a...', 'El Hoy no Circula para la CDMX y el Edomex entra en vigor a las 5:00 y termina a las 22:00 horas; tiene como objetivo disminuir la contaminación del aire.

Luego de que la Ciudad de México tuviera varios días de Doble Hoy No Circula , todo vuelve a la normalidad, aunque se reportó mala calidad del aire el miércoles 18 de febrero .

Al corte de las 17:00 horas de este miércoles 18 de febrero , las autoridades medioambientales reportaron mala calidad del aire , con presencia de partículas de ozono .

No se ha determinado que para el jueves 19 de febrero haya un Doble Hoy No Circula por contingencia ambiental, por lo que el programa operará con normalidad.

Además, considera si a diario usas el Metro de la Ciudad de México , considera que la Línea 2 estará en obras, por lo que habrá servicio de RTP para varias estaciones.

En las 16 alcaldías de la CDMX y en los 18 municipios colindantes del Estado de México te pueden multar si no respetas el Hoy No Circula .

La restricción vehicular, que entra en vigor a las 5:00 y termina a las 22:00 horas, tiene como objetivo disminuir la contaminación del aire y mejorar la calidad ambiental en la Zona M', 1156, 'centralmexico', 'Nacional', '2026-02-18T23:52:16Z', 'Redacción', 1, 'https://www.elfinanciero.com.mx/resizer/v2/I7SZUWS4ZZEYTH7TJ3KYND2BUI.jpeg?smart=true&auth=8fe12fe9a260fc27e29a669cddaff102ddbcd9b3fbb55d9065bee22c4d8873fc&width=1200&height=630'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://actualidad.rt.com/actualidad/587813-hallan-fosa-clandestina-seis-cuerpos', 'https://actualidad.rt.com/actualidad/587813-hallan-fosa-clandestina-seis-cuerpos', 'Hallan fosa clandestina con varios cuerpos en México que llevaba años sin ser descubierta', 'La Fiscalía General del Estado de Tabasco informó este miércoles del hallazgo de una fosa clandestina con seis cuerpos en un predio del municipio de Paraíso, en el sureste del país. El descubrimiento fue realizado por peritos forenses en coordinación con la Comisión Estatal de Búsqueda, y las autori...', 'https://mfes.b37m.ru/actualidad/public_images/2026.02/original/69964ffde9ff7133685a86f8.jpg', '2026-02-18T23:49:17Z', 'La Fiscalía General del Estado de Tabasco informó este miércoles del hallazgo de una fosa clandestina con seis cuerpos en un predio del municipio de Paraíso, en el sureste del país. El descubrimiento fue realizado por peritos forenses en coordinación con la Comisión Estatal de Búsqueda, y las autoridades estiman que los restos tendrían una antigüedad de entre 3 y 5 años, por lo que ya trabajan en su identificación.

El sitio tendría una extensión aproximada de 75 metros y se investiga si el hallazgo está relacionado con otra fosa localizada el 10 de febrero en la misma zona, aunque hasta el momento no se ha confirmado si se trata del mismo lugar. El caso se produce en un contexto de violencia persistente en el estado, donde se han registrado homicidios y otros hechos de alto impacto en los últimos meses.

⚪Comunicado. La #FGET y la Comisión Estatal de Búsqueda trabajan de manera conjunta en el municipio de Paraíso. pic.twitter.com/ZHr37JsEYK', 'Nacional'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://actualidad.rt.com/actualidad/587813-hallan-fosa-clandestina-seis-cuerpos', 'Hallan fosa clandestina con varios cuerpos en México que llevaba años sin ser descubierta', 'La Fiscalía General del Estado de Tabasco informó este miércoles del hallazgo de una fosa clandestina con seis cuerpos en un predio del municipio de Paraíso, en el sureste del país. El descubrimiento fue realizado por peritos forenses en coordinación con la Comisión Estatal de Búsqueda, y las autori...', 'La Fiscalía General del Estado de Tabasco informó este miércoles del hallazgo de una fosa clandestina con seis cuerpos en un predio del municipio de Paraíso, en el sureste del país. El descubrimiento fue realizado por peritos forenses en coordinación con la Comisión Estatal de Búsqueda, y las autoridades estiman que los restos tendrían una antigüedad de entre 3 y 5 años, por lo que ya trabajan en su identificación.

El sitio tendría una extensión aproximada de 75 metros y se investiga si el hallazgo está relacionado con otra fosa localizada el 10 de febrero en la misma zona, aunque hasta el momento no se ha confirmado si se trata del mismo lugar. El caso se produce en un contexto de violencia persistente en el estado, donde se han registrado homicidios y otros hechos de alto impacto en los últimos meses.

⚪Comunicado. La #FGET y la Comisión Estatal de Búsqueda trabajan de manera conjunta en el municipio de Paraíso. pic.twitter.com/ZHr37JsEYK', 955, 'mexicoinformado', 'Nacional', '2026-02-18T23:49:17Z', 'RT en Español
 , RT en Español', 0, 'https://mfes.b37m.ru/actualidad/public_images/2026.02/original/69964ffde9ff7133685a86f8.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.milenio.com/deportes/futbol-internacional/claudia-cid-denuncia-abandono-de-su-club-tras-grave-lesion', 'https://www.milenio.com/deportes/futbol-internacional/claudia-cid-denuncia-abandono-de-su-club-tras-grave-lesion', 'Sueño europeo roto: Claudia Cid denuncia abandono de su club tras grave lesión', 'La historia de Claudia Cid, ex futbolista de la Liga MX Femenil, pasó de ser el reflejo de un sueño cumplido a convertirse en una denuncia pública sobre la vulnerabilidad que pueden enfrentar las jugadoras o jugadores que emigran al extranjero. La mexicana de…

Para ver esta página correctamente, ne...', 'https://cdn.milenio.com/uploads/media/2026/02/18/sueno-europeo-roto-claudia-cid.jpg', '2026-02-18T23:49:00Z', 'La historia de Claudia Cid, ex futbolista de la Liga MX Femenil, pasó de ser el reflejo de un sueño cumplido a convertirse en una denuncia pública sobre la vulnerabilidad que pueden enfrentar las jugadoras o jugadores que emigran al extranjero. La mexicana de…

Para ver esta página correctamente, necesitas activar JavaScript en tu navegador.

La historia de Claudia Cid , ex futbolista de la Liga MX Femenil , pasó de ser el reflejo de un sueño cumplido a convertirse en una denuncia pública sobre la vulnerabilidad que pueden enfrentar las jugadoras o jugadores que emigran al extranjero. La mexicana decidió viajar a Andorra con la ilusión de consolidar una carrera en Europa , motivada por la promesa de competir en torneos internacionales y crecer profesionalmente; sin embargo, una grave lesión de rodilla cambió por completo el rumbo de su experiencia y la colocó en una situación médica y económica crítica, luego de que su club se deslindara de la responsabilidad de su operación.

La jugadora platicó con Milenio- La Afición y relató que su llegada al futbol europeo estuvo llena de expectativas y confianza, pues aceptó la oferta tras recibir garantías deportivas y administrativas .

El problema surgió cuando sufrió la lesión el 4cuatro de diciembr', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.milenio.com/deportes/futbol-internacional/claudia-cid-denuncia-abandono-de-su-club-tras-grave-lesion', 'Sueño europeo roto: Claudia Cid denuncia abandono de su club tras grave lesión', 'La historia de Claudia Cid, ex futbolista de la Liga MX Femenil, pasó de ser el reflejo de un sueño cumplido a convertirse en una denuncia pública sobre la vulnerabilidad que pueden enfrentar las jugadoras o jugadores que emigran al extranjero. La mexicana de…

Para ver esta página correctamente, ne...', 'La historia de Claudia Cid, ex futbolista de la Liga MX Femenil, pasó de ser el reflejo de un sueño cumplido a convertirse en una denuncia pública sobre la vulnerabilidad que pueden enfrentar las jugadoras o jugadores que emigran al extranjero. La mexicana de…

Para ver esta página correctamente, necesitas activar JavaScript en tu navegador.

La historia de Claudia Cid , ex futbolista de la Liga MX Femenil , pasó de ser el reflejo de un sueño cumplido a convertirse en una denuncia pública sobre la vulnerabilidad que pueden enfrentar las jugadoras o jugadores que emigran al extranjero. La mexicana decidió viajar a Andorra con la ilusión de consolidar una carrera en Europa , motivada por la promesa de competir en torneos internacionales y crecer profesionalmente; sin embargo, una grave lesión de rodilla cambió por completo el rumbo de su experiencia y la colocó en una situación médica y económica crítica, luego de que su club se deslindara de la responsabilidad de su operación.

La jugadora platicó con Milenio- La Afición y relató que su llegada al futbol europeo estuvo llena de expectativas y confianza, pues aceptó la oferta tras recibir garantías deportivas y administrativas .

El problema surgió cuando sufrió la lesión el 4cuatro de diciembr', 1262, 'nodoinformativo', 'Tecnología', '2026-02-18T23:49:00Z', 'Minelli Atayde Zarco', 0, 'https://cdn.milenio.com/uploads/media/2026/02/18/sueno-europeo-roto-claudia-cid.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.milenio.com/policia/asistencia-consular-penal-para-mexicanos-detenidos-no-testigos-corte', 'https://www.milenio.com/policia/asistencia-consular-penal-para-mexicanos-detenidos-no-testigos-corte', 'Asistencia consular en casos penales, solo para mexicanos detenidos en el extranjero, no para testigos: Corte', 'La Suprema Corte de Justicia de la Nación (SCJN) determinó que la asistencia consular en casos penales solo opera para los mexicanos detenidos en el extranjero, pero no para los que declaran en calidad de testigos.El pronunciamiento de la Corte derivó de un a…

La Suprema Corte de Justicia de la Nac...', 'https://cdn.milenio.com/uploads/media/2026/02/18/sesion-pleno-suprema-corte-justicia.jpg', '2026-02-18T23:46:00Z', 'La Suprema Corte de Justicia de la Nación (SCJN) determinó que la asistencia consular en casos penales solo opera para los mexicanos detenidos en el extranjero, pero no para los que declaran en calidad de testigos.El pronunciamiento de la Corte derivó de un a…

La Suprema Corte de Justicia de la Nación (SCJN) determinó que la asistencia consular en casos penales solo opera para los mexicanos detenidos en el extranjero, pero no para los que declaran en calid… [+2534 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.milenio.com/policia/asistencia-consular-penal-para-mexicanos-detenidos-no-testigos-corte', 'Asistencia consular en casos penales, solo para mexicanos detenidos en el extranjero, no para testigos: Corte', 'La Suprema Corte de Justicia de la Nación (SCJN) determinó que la asistencia consular en casos penales solo opera para los mexicanos detenidos en el extranjero, pero no para los que declaran en calidad de testigos.El pronunciamiento de la Corte derivó de un a…

La Suprema Corte de Justicia de la Nac...', 'La Suprema Corte de Justicia de la Nación (SCJN) determinó que la asistencia consular en casos penales solo opera para los mexicanos detenidos en el extranjero, pero no para los que declaran en calidad de testigos.El pronunciamiento de la Corte derivó de un a…

La Suprema Corte de Justicia de la Nación (SCJN) determinó que la asistencia consular en casos penales solo opera para los mexicanos detenidos en el extranjero, pero no para los que declaran en calid… [+2534 chars]', 476, 'noticiasobjetivo', 'Tecnología', '2026-02-18T23:46:00Z', 'Rubén Mosso', 0, 'https://cdn.milenio.com/uploads/media/2026/02/18/sesion-pleno-suprema-corte-justicia.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.milenio.com/negocios/canada-mexico-buscan-trilateral-revision-t-mec', 'https://www.milenio.com/negocios/canada-mexico-buscan-trilateral-revision-t-mec', 'México, interesado en mantener el pacto trilateral: ministro canadiense tras reunión con Ebrard', 'El ministro del gobierno canadiense que representará a Ottawa en la revisión del ⁠tratado comercial de Norteamérica (T-MEC) dijo que México está interesado en mantener el pacto trilateral entre Canadá, Estados Unidos y México, que se revisará este año."Me tra…

El ministro del gobierno canadiense qu...', 'https://cdn.milenio.com/uploads/media/2025/09/22/morena-invita-participar-consulta-t.jpeg', '2026-02-18T23:45:00Z', 'El ministro del gobierno canadiense que representará a Ottawa en la revisión del ⁠tratado comercial de Norteamérica (T-MEC) dijo que México está interesado en mantener el pacto trilateral entre Canadá, Estados Unidos y México, que se revisará este año."Me tra…

El ministro del gobierno canadiense que representará a Ottawa en la revisión del tratado comercial de Norteamérica (T-MEC) dijo que México está interesado en mantener el pacto trilateral entre Canadá… [+608 chars]', 'Política'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.milenio.com/negocios/canada-mexico-buscan-trilateral-revision-t-mec', 'México, interesado en mantener el pacto trilateral: ministro canadiense tras reunión con Ebrard', 'El ministro del gobierno canadiense que representará a Ottawa en la revisión del ⁠tratado comercial de Norteamérica (T-MEC) dijo que México está interesado en mantener el pacto trilateral entre Canadá, Estados Unidos y México, que se revisará este año."Me tra…

El ministro del gobierno canadiense qu...', 'El ministro del gobierno canadiense que representará a Ottawa en la revisión del ⁠tratado comercial de Norteamérica (T-MEC) dijo que México está interesado en mantener el pacto trilateral entre Canadá, Estados Unidos y México, que se revisará este año."Me tra…

El ministro del gobierno canadiense que representará a Ottawa en la revisión del tratado comercial de Norteamérica (T-MEC) dijo que México está interesado en mantener el pacto trilateral entre Canadá… [+608 chars]', 475, 'radiocinconoticias', 'Política', '2026-02-18T23:45:00Z', 'Agencia Reuters', 0, 'https://cdn.milenio.com/uploads/media/2025/09/22/morena-invita-participar-consulta-t.jpeg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.milenio.com/espectaculos/cine/bastian-escobar-nino-actor-deslumbra-berlinale-2026', 'https://www.milenio.com/espectaculos/cine/bastian-escobar-nino-actor-deslumbra-berlinale-2026', 'Bastian Escobar, el actor mexicano de 9 años que sorprende en el Festival de Cine de Berlín', 'Moscas, la nueva película de Fernando Eimbcke (Temporada de patos), se presentó este miércoles en el Festival Internacional de Cine de Berlín, sorprendiendo por nivel actoral y carisma de uno de sus protagonistas: Bastian Escobar, quien solo tiene nueve añosD…

Moscas, la nueva película de Fernando ...', 'https://cdn.milenio.com/uploads/media/2026/02/18/bastian-director-cinta-fernando-eimbcke.jpg', '2026-02-18T23:45:00Z', 'Moscas, la nueva película de Fernando Eimbcke (Temporada de patos), se presentó este miércoles en el Festival Internacional de Cine de Berlín, sorprendiendo por nivel actoral y carisma de uno de sus protagonistas: Bastian Escobar, quien solo tiene nueve añosD…

Moscas, la nueva película de Fernando Eimbcke (Temporada de patos), se presentó este miércoles en el Festival Internacional de Cine de Berlín, sorprendiendo por nivel actoral y carisma de uno de sus … [+3267 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.milenio.com/espectaculos/cine/bastian-escobar-nino-actor-deslumbra-berlinale-2026', 'Bastian Escobar, el actor mexicano de 9 años que sorprende en el Festival de Cine de Berlín', 'Moscas, la nueva película de Fernando Eimbcke (Temporada de patos), se presentó este miércoles en el Festival Internacional de Cine de Berlín, sorprendiendo por nivel actoral y carisma de uno de sus protagonistas: Bastian Escobar, quien solo tiene nueve añosD…

Moscas, la nueva película de Fernando ...', 'Moscas, la nueva película de Fernando Eimbcke (Temporada de patos), se presentó este miércoles en el Festival Internacional de Cine de Berlín, sorprendiendo por nivel actoral y carisma de uno de sus protagonistas: Bastian Escobar, quien solo tiene nueve añosD…

Moscas, la nueva película de Fernando Eimbcke (Temporada de patos), se presentó este miércoles en el Festival Internacional de Cine de Berlín, sorprendiendo por nivel actoral y carisma de uno de sus … [+3267 chars]', 476, 'reportecentralmx', 'Tecnología', '2026-02-18T23:45:00Z', 'Milenio Entretenimiento', 0, 'https://cdn.milenio.com/uploads/media/2026/02/18/bastian-director-cinta-fernando-eimbcke.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://exitoina.perfil.com/noticias/musica/twenty-one-pilots-sorprendio-al-lanzar-oficialmente-su-sencillo-drag-path-tras-varias-filtraciones-en-redes.phtml', 'https://exitoina.perfil.com/noticias/musica/twenty-one-pilots-sorprendio-al-lanzar-oficialmente-su-sencillo-drag-path-tras-varias-filtraciones-en-redes.phtml', 'Twenty One Pilots sorprendió al lanzar oficialmente su sencillo "Drag Path" tras varias filtraciones en redes', 'Hasta hoy, esta canción solo se podía encontrar en "Breach: Digital Remains", la edición limitada que expandía su álbum "Breach". Leer más

Twenty One Pilots sorprendió a sus fieles seguidores este miércoles 18 de febrero al lanzar "Drag Path", que llega a plataformas oficiales tras viralizarse por ...', 'https://fotos.perfil.com/2026/02/18/trim/1140/641/twenty-one-pilots-2188347.jpg', '2026-02-18T23:40:46Z', 'Hasta hoy, esta canción solo se podía encontrar en "Breach: Digital Remains", la edición limitada que expandía su álbum "Breach". Leer más

Twenty One Pilots sorprendió a sus fieles seguidores este miércoles 18 de febrero al lanzar "Drag Path", que llega a plataformas oficiales tras viralizarse por sus filtraciones. Recordemos que hasta … [+1381 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://exitoina.perfil.com/noticias/musica/twenty-one-pilots-sorprendio-al-lanzar-oficialmente-su-sencillo-drag-path-tras-varias-filtraciones-en-redes.phtml', 'Twenty One Pilots sorprendió al lanzar oficialmente su sencillo "Drag Path" tras varias filtraciones en redes', 'Hasta hoy, esta canción solo se podía encontrar en "Breach: Digital Remains", la edición limitada que expandía su álbum "Breach". Leer más

Twenty One Pilots sorprendió a sus fieles seguidores este miércoles 18 de febrero al lanzar "Drag Path", que llega a plataformas oficiales tras viralizarse por ...', 'Hasta hoy, esta canción solo se podía encontrar en "Breach: Digital Remains", la edición limitada que expandía su álbum "Breach". Leer más

Twenty One Pilots sorprendió a sus fieles seguidores este miércoles 18 de febrero al lanzar "Drag Path", que llega a plataformas oficiales tras viralizarse por sus filtraciones. Recordemos que hasta … [+1381 chars]', 354, 'tvmexico', 'Tecnología', '2026-02-18T23:40:46Z', 'Johanna Chiesa', 0, 'https://fotos.perfil.com/2026/02/18/trim/1140/641/twenty-one-pilots-2188347.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.lanacion.com.ar/politica/en-un-dia-caliente-para-el-gobierno-milei-llega-a-washington-para-la-reunion-del-consejo-de-la-paz-nid18022026/', 'https://www.lanacion.com.ar/politica/en-un-dia-caliente-para-el-gobierno-milei-llega-a-washington-para-la-reunion-del-consejo-de-la-paz-nid18022026/', 'En un día caliente para el Gobierno, Milei llega a Washington para la reunión del Consejo de la Paz que convocó Trump', 'El Presidente participará el jueves de la sesión inaugural de la entidad, en la que se tratará la reconstrucción de Gaza; en el viaje exprés lo acompañan Karina Milei y el canciller Quirno

WASHINGTON.- Javier Milei llega esta noche a Washington en un viaje exprés para participar el jueves de la ses...', 'https://resizer.glanacion.com/resizer/v2/los-presidentes-donald-trump-y-javier-milei-en-el-W5FWCFLROREU5I6TJQ5QWQC6VE.jpg?auth=cb6a488f4075a9cfced1ad9fa3a63211aca15b9f40453ce1ef63bceb5c636a9c&width=1200&quality=70&smart=false&height=800', '2026-02-18T23:30:37Z', 'El Presidente participará el jueves de la sesión inaugural de la entidad, en la que se tratará la reconstrucción de Gaza; en el viaje exprés lo acompañan Karina Milei y el canciller Quirno

WASHINGTON.- Javier Milei llega esta noche a Washington en un viaje exprés para participar el jueves de la sesión inaugural del Consejo de la Paz convocada por su principal aliado internacional, el p… [+6513 chars]', 'Política'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.lanacion.com.ar/politica/en-un-dia-caliente-para-el-gobierno-milei-llega-a-washington-para-la-reunion-del-consejo-de-la-paz-nid18022026/', 'En un día caliente para el Gobierno, Milei llega a Washington para la reunión del Consejo de la Paz que convocó Trump', 'El Presidente participará el jueves de la sesión inaugural de la entidad, en la que se tratará la reconstrucción de Gaza; en el viaje exprés lo acompañan Karina Milei y el canciller Quirno

WASHINGTON.- Javier Milei llega esta noche a Washington en un viaje exprés para participar el jueves de la ses...', 'El Presidente participará el jueves de la sesión inaugural de la entidad, en la que se tratará la reconstrucción de Gaza; en el viaje exprés lo acompañan Karina Milei y el canciller Quirno

WASHINGTON.- Javier Milei llega esta noche a Washington en un viaje exprés para participar el jueves de la sesión inaugural del Consejo de la Paz convocada por su principal aliado internacional, el p… [+6513 chars]', 404, 'verticenoticias', 'Política', '2026-02-18T23:30:37Z', 'Guillermo Idiart', 0, 'https://resizer.glanacion.com/resizer/v2/los-presidentes-donald-trump-y-javier-milei-en-el-W5FWCFLROREU5I6TJQ5QWQC6VE.jpg?auth=cb6a488f4075a9cfced1ad9fa3a63211aca15b9f40453ce1ef63bceb5c636a9c&width=1200&quality=70&smart=false&height=800'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.milenio.com/negocios/banco-base-senala-interes-empresas-extranjeras-mexico', 'https://www.milenio.com/negocios/banco-base-senala-interes-empresas-extranjeras-mexico', '“Vendrán como tsunami de inversión”: Banco Base señala interés de empresas extranjeras en México', 'A pesar de la volatilidad registrada en el sector empresario, Banco Base percibe interés por parte de compañías extranjeras para invertir en México.“Las empresas extranjeras “están pagando por ver”, ya que en el momento esto se destrabe, van a empezar a venir…

A pesar de la volatilidad registrada e...', 'https://cdn.milenio.com/uploads/media/2023/08/21/puebla-capta-ied-mil-mdd.jpg', '2026-02-18T23:28:00Z', 'A pesar de la volatilidad registrada en el sector empresario, Banco Base percibe interés por parte de compañías extranjeras para invertir en México.“Las empresas extranjeras “están pagando por ver”, ya que en el momento esto se destrabe, van a empezar a venir…

A pesar de la volatilidad registrada en el sector empresario, Banco Base percibe interés por parte de compañías extranjeras para invertir en México.
Las empresas extranjeras están pagando por ver, y… [+2661 chars]', 'Economía'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.milenio.com/negocios/banco-base-senala-interes-empresas-extranjeras-mexico', '“Vendrán como tsunami de inversión”: Banco Base señala interés de empresas extranjeras en México', 'A pesar de la volatilidad registrada en el sector empresario, Banco Base percibe interés por parte de compañías extranjeras para invertir en México.“Las empresas extranjeras “están pagando por ver”, ya que en el momento esto se destrabe, van a empezar a venir…

A pesar de la volatilidad registrada e...', 'A pesar de la volatilidad registrada en el sector empresario, Banco Base percibe interés por parte de compañías extranjeras para invertir en México.“Las empresas extranjeras “están pagando por ver”, ya que en el momento esto se destrabe, van a empezar a venir…

A pesar de la volatilidad registrada en el sector empresario, Banco Base percibe interés por parte de compañías extranjeras para invertir en México.
Las empresas extranjeras están pagando por ver, y… [+2661 chars]', 476, 'bitacoraurbana', 'Economía', '2026-02-18T23:28:00Z', 'Fernanda Murillo', 0, 'https://cdn.milenio.com/uploads/media/2023/08/21/puebla-capta-ied-mil-mdd.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.elfinanciero.com.mx/food-and-drink/2026/02/18/festival-internacional-del-taco-y-el-asado-2026-fechas-sede-actividades-y-lo-que-debes-saber/', 'https://www.elfinanciero.com.mx/food-and-drink/2026/02/18/festival-internacional-del-taco-y-el-asado-2026-fechas-sede-actividades-y-lo-que-debes-saber/', 'Festival Internacional del Taco y el Asado 2026: Fechas, sede, actividades y lo que debes saber', 'El Festival Internacional del Taco informó que se espera la participación de cocineros de otros tipos de platillos como alitas y espadas brasileñas.

¡Pa echarse un taquito y una carnita asada! El Festival Internacional del Taco y el Asado anunció las fechas y la sede del evento de comida mexicana d...', 'https://www.elfinanciero.com.mx/resizer/v2/RL5FET4NAZARTOLIT2WKXZCFRQ.jpg?smart=true&auth=56dff8f9f5c8cb2b84002103e82c72ed4c2970d57b2bef6e545c0f5260f00ebf&width=1200&height=630', '2026-02-18T23:17:34Z', 'El Festival Internacional del Taco informó que se espera la participación de cocineros de otros tipos de platillos como alitas y espadas brasileñas.

¡Pa echarse un taquito y una carnita asada! El Festival Internacional del Taco y el Asado anunció las fechas y la sede del evento de comida mexicana donde acuden alrededor de 100 expositores con sus … [+2672 chars]', 'Cultura'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.elfinanciero.com.mx/food-and-drink/2026/02/18/festival-internacional-del-taco-y-el-asado-2026-fechas-sede-actividades-y-lo-que-debes-saber/', 'Festival Internacional del Taco y el Asado 2026: Fechas, sede, actividades y lo que debes saber', 'El Festival Internacional del Taco informó que se espera la participación de cocineros de otros tipos de platillos como alitas y espadas brasileñas.

¡Pa echarse un taquito y una carnita asada! El Festival Internacional del Taco y el Asado anunció las fechas y la sede del evento de comida mexicana d...', 'El Festival Internacional del Taco informó que se espera la participación de cocineros de otros tipos de platillos como alitas y espadas brasileñas.

¡Pa echarse un taquito y una carnita asada! El Festival Internacional del Taco y el Asado anunció las fechas y la sede del evento de comida mexicana donde acuden alrededor de 100 expositores con sus … [+2672 chars]', 364, 'cbnnoticias', 'Cultura', '2026-02-18T23:17:34Z', 'Redacción', 0, 'https://www.elfinanciero.com.mx/resizer/v2/RL5FET4NAZARTOLIT2WKXZCFRQ.jpg?smart=true&auth=56dff8f9f5c8cb2b84002103e82c72ed4c2970d57b2bef6e545c0f5260f00ebf&width=1200&height=630'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://actualidad.rt.com/actualidad/587809-ataque-tiros-parque-mexico-deja', 'https://actualidad.rt.com/actualidad/587809-ataque-tiros-parque-mexico-deja', 'Ataque a tiros en un parque de México deja un muerto y 10 heridos, varios de ellos niños', 'Una persona murió y otras 10 resultaron heridas —la mayoría menores de edad— en un ataque armado ocurrido la noche del martes en un parque de la colonia Renovación, municipio de San Francisco del Rin… [+843 chars]', 'https://mfes.b37m.ru/actualidad/public_images/2026.02/original/6996481c59bf5b775f465f47.jpg', '2026-02-18T23:15:40Z', 'Una persona murió y otras 10 resultaron heridas —la mayoría menores de edad— en un ataque armado ocurrido la noche del martes en un parque de la colonia Renovación, municipio de San Francisco del Rin… [+843 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://actualidad.rt.com/actualidad/587809-ataque-tiros-parque-mexico-deja', 'Ataque a tiros en un parque de México deja un muerto y 10 heridos, varios de ellos niños', 'Una persona murió y otras 10 resultaron heridas —la mayoría menores de edad— en un ataque armado ocurrido la noche del martes en un parque de la colonia Renovación, municipio de San Francisco del Rin… [+843 chars]', 'Una persona murió y otras 10 resultaron heridas —la mayoría menores de edad— en un ataque armado ocurrido la noche del martes en un parque de la colonia Renovación, municipio de San Francisco del Rin… [+843 chars]', 213, 'centralmexico', 'Tecnología', '2026-02-18T23:15:40Z', 'RT en Español
 , RT en Español', 0, 'https://mfes.b37m.ru/actualidad/public_images/2026.02/original/6996481c59bf5b775f465f47.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.elfinanciero.com.mx/espectaculos/2026/02/18/sergio-mayer-afirma-que-llego-a-la-politica-sin-ayuda-de-su-suegro-jaime-camil-garza/', 'https://www.elfinanciero.com.mx/espectaculos/2026/02/18/sergio-mayer-afirma-que-llego-a-la-politica-sin-ayuda-de-su-suegro-jaime-camil-garza/', '‘Mi suegro ayudó a mucha gente en el PRI’: Sergio Mayer afirma que llegó solo a la política', 'Sergio Mayer entra a La Casa de los Famosos y revive sus palabras sobre Jaime Camil Garza, el empresario y suegro que marcó su vida familiar y política.

El actor y político Sergio Mayerha defendido que el empresario Jaime Camil Garza, su finado suegro, no le ayudó para comenzar su carrera política,...', 'https://www.elfinanciero.com.mx/resizer/v2/FW4F4BGF4RA75HMUOCK6B45K4U.jpg?smart=true&auth=3ae6426e5f472424dbe6ca9ff905f270230863d74c6103425646aa18975c61ee&width=1200&height=630', '2026-02-18T23:12:01Z', 'Sergio Mayer entra a La Casa de los Famosos y revive sus palabras sobre Jaime Camil Garza, el empresario y suegro que marcó su vida familiar y política.

El actor y político Sergio Mayerha defendido que el empresario Jaime Camil Garza, su finado suegro, no le ayudó para comenzar su carrera política, sino que la forjó personalmente.
Recientemente, May… [+6230 chars]', 'Política'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.elfinanciero.com.mx/espectaculos/2026/02/18/sergio-mayer-afirma-que-llego-a-la-politica-sin-ayuda-de-su-suegro-jaime-camil-garza/', '‘Mi suegro ayudó a mucha gente en el PRI’: Sergio Mayer afirma que llegó solo a la política', 'Sergio Mayer entra a La Casa de los Famosos y revive sus palabras sobre Jaime Camil Garza, el empresario y suegro que marcó su vida familiar y política.

El actor y político Sergio Mayerha defendido que el empresario Jaime Camil Garza, su finado suegro, no le ayudó para comenzar su carrera política,...', 'Sergio Mayer entra a La Casa de los Famosos y revive sus palabras sobre Jaime Camil Garza, el empresario y suegro que marcó su vida familiar y política.

El actor y político Sergio Mayerha defendido que el empresario Jaime Camil Garza, su finado suegro, no le ayudó para comenzar su carrera política, sino que la forjó personalmente.
Recientemente, May… [+6230 chars]', 368, 'mexicoinformado', 'Política', '2026-02-18T23:12:01Z', 'Redacción', 0, 'https://www.elfinanciero.com.mx/resizer/v2/FW4F4BGF4RA75HMUOCK6B45K4U.jpg?smart=true&auth=3ae6426e5f472424dbe6ca9ff905f270230863d74c6103425646aa18975c61ee&width=1200&height=630'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.elfinanciero.com.mx/deportes/2026/02/18/cuales-son-los-posibles-rivales-de-san-francisco-49ers-en-el-estadio-azteca-banorte/', 'https://www.elfinanciero.com.mx/deportes/2026/02/18/cuales-son-los-posibles-rivales-de-san-francisco-49ers-en-el-estadio-azteca-banorte/', '¿Cuáles son los posibles rivales de San Francisco 49ers en el Estadio Azteca-Banorte?', 'Posibles rivales de los 49ers en México 2026: Vikings, Raiders, Eagles y más equipos que podrían jugar en el Estadio Azteca-Banorte.

Los San Francisco 49ers jugarán en México como locales un partido de temporada regular de la NFL en el remodelado Estadio Azteca-Banorte, con rival aún por anunciar.....', 'https://www.elfinanciero.com.mx/resizer/v2/T4AVAVUN2JCDBHQEEFMEPNJPNQ.jpeg?smart=true&auth=f604ab89efb2b4dc1f281d724bad8348aa8f8a1ffc48fea808dd753c43b196bc&width=1200&height=630', '2026-02-18T23:11:52Z', 'Posibles rivales de los 49ers en México 2026: Vikings, Raiders, Eagles y más equipos que podrían jugar en el Estadio Azteca-Banorte.

Los San Francisco 49ers jugarán en México como locales un partido de temporada regular de la NFL en el remodelado Estadio Azteca-Banorte, con rival aún por anunciar... aunque ya hay candidatos.
Y es… [+3163 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.elfinanciero.com.mx/deportes/2026/02/18/cuales-son-los-posibles-rivales-de-san-francisco-49ers-en-el-estadio-azteca-banorte/', '¿Cuáles son los posibles rivales de San Francisco 49ers en el Estadio Azteca-Banorte?', 'Posibles rivales de los 49ers en México 2026: Vikings, Raiders, Eagles y más equipos que podrían jugar en el Estadio Azteca-Banorte.

Los San Francisco 49ers jugarán en México como locales un partido de temporada regular de la NFL en el remodelado Estadio Azteca-Banorte, con rival aún por anunciar.....', 'Posibles rivales de los 49ers en México 2026: Vikings, Raiders, Eagles y más equipos que podrían jugar en el Estadio Azteca-Banorte.

Los San Francisco 49ers jugarán en México como locales un partido de temporada regular de la NFL en el remodelado Estadio Azteca-Banorte, con rival aún por anunciar... aunque ya hay candidatos.
Y es… [+3163 chars]', 348, 'nodoinformativo', 'Tecnología', '2026-02-18T23:11:52Z', 'Redacción', 0, 'https://www.elfinanciero.com.mx/resizer/v2/T4AVAVUN2JCDBHQEEFMEPNJPNQ.jpeg?smart=true&auth=f604ab89efb2b4dc1f281d724bad8348aa8f8a1ffc48fea808dd753c43b196bc&width=1200&height=630'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.elpais.com.uy/enlaces-patrocinados/am-best-afirma-calificaciones-crediticias-de-compania-internacional-de-seguros-s-a-20260218', 'https://www.elpais.com.uy/enlaces-patrocinados/am-best-afirma-calificaciones-crediticias-de-compania-internacional-de-seguros-s-a-20260218', 'AM Best Afirma Calificaciones Crediticias de Compañía Internacional de Seguros, S.A.', 'CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM Best ha afirmado la Calificación de Fortaleza Financiera de A (Excelente) y la Calificación Crediticia de Emisor de Largo Plazo de “a” (Excelente) de Compañía Internacional de Seguros, S.A. (CIS) (Ciudad de Panamá, Panamá…

CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM ...', 'https://imgs.elpais.com.uy/dims4/default/6bfc0ab/2147483647/strip/true/crop/1440x700+0+0/resize/1440x700!/quality/90/?url=https%3A%2F%2Fel-pais-uruguay-production-web.s3.us-east-1.amazonaws.com%2Fbrightspot%2Fc5%2Ff9%2F5af15c6a49008f02d397c5e0d189%2Fdescarga.jpeg', '2026-02-18T23:10:30Z', 'CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM Best ha afirmado la Calificación de Fortaleza Financiera de A (Excelente) y la Calificación Crediticia de Emisor de Largo Plazo de “a” (Excelente) de Compañía Internacional de Seguros, S.A. (CIS) (Ciudad de Panamá, Panamá…

CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM Best ha afirmado la Calificación de Fortaleza Financiera de A (Excelente) y la Calificación Crediticia de Emisor de Largo Plazo de a (Excelente) de Compañía Inte… [+5287 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.elpais.com.uy/enlaces-patrocinados/am-best-afirma-calificaciones-crediticias-de-compania-internacional-de-seguros-s-a-20260218', 'AM Best Afirma Calificaciones Crediticias de Compañía Internacional de Seguros, S.A.', 'CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM Best ha afirmado la Calificación de Fortaleza Financiera de A (Excelente) y la Calificación Crediticia de Emisor de Largo Plazo de “a” (Excelente) de Compañía Internacional de Seguros, S.A. (CIS) (Ciudad de Panamá, Panamá…

CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM ...', 'CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM Best ha afirmado la Calificación de Fortaleza Financiera de A (Excelente) y la Calificación Crediticia de Emisor de Largo Plazo de “a” (Excelente) de Compañía Internacional de Seguros, S.A. (CIS) (Ciudad de Panamá, Panamá…

CIUDAD DE MÉXICO--(BUSINESS WIRE)--AM Best ha afirmado la Calificación de Fortaleza Financiera de A (Excelente) y la Calificación Crediticia de Emisor de Largo Plazo de a (Excelente) de Compañía Inte… [+5287 chars]', 476, 'noticiasobjetivo', 'Tecnología', '2026-02-18T23:10:30Z', 'Redacción', 0, 'https://imgs.elpais.com.uy/dims4/default/6bfc0ab/2147483647/strip/true/crop/1440x700+0+0/resize/1440x700!/quality/90/?url=https%3A%2F%2Fel-pais-uruguay-production-web.s3.us-east-1.amazonaws.com%2Fbrightspot%2Fc5%2Ff9%2F5af15c6a49008f02d397c5e0d189%2Fdescarga.jpeg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.milenio.com/futbol/liga-mx/ricardo-la-volpe-sobre-chivas-esperemos-que-salga-campeon-de-liga-mx', 'https://www.milenio.com/futbol/liga-mx/ricardo-la-volpe-sobre-chivas-esperemos-que-salga-campeon-de-liga-mx', 'Ricardo La Volpe reconoce a Chivas como uno de los mejores equipos de la Liga MX', 'Las Chivas de Gabriel Milito es uno de los mejores equipos en la Liga MX, así lo ve Ricardo La Volpe.El ex técnico de la Selección Mexicana en el Mundial de Alemania 2006 elogió la forma de juego del chiverío, que marcha como líder de la tabla con seis victor…

Las Chivas de Gabriel Milito es uno de...', 'https://cdn.milenio.com/uploads/media/2026/02/18/ricardo-volpe-ve-chivas-mejores.jpg', '2026-02-18T23:06:00Z', 'Las Chivas de Gabriel Milito es uno de los mejores equipos en la Liga MX, así lo ve Ricardo La Volpe.El ex técnico de la Selección Mexicana en el Mundial de Alemania 2006 elogió la forma de juego del chiverío, que marcha como líder de la tabla con seis victor…

Las Chivas de Gabriel Milito es uno de los mejores equipos en la Liga MX, así lo ve Ricardo La Volpe.
El ex técnico de la Selección Mexicana en el Mundial de Alemania 2006 elogió la forma de juego d… [+1508 chars]', 'Política'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.milenio.com/futbol/liga-mx/ricardo-la-volpe-sobre-chivas-esperemos-que-salga-campeon-de-liga-mx', 'Ricardo La Volpe reconoce a Chivas como uno de los mejores equipos de la Liga MX', 'Las Chivas de Gabriel Milito es uno de los mejores equipos en la Liga MX, así lo ve Ricardo La Volpe.El ex técnico de la Selección Mexicana en el Mundial de Alemania 2006 elogió la forma de juego del chiverío, que marcha como líder de la tabla con seis victor…

Las Chivas de Gabriel Milito es uno de...', 'Las Chivas de Gabriel Milito es uno de los mejores equipos en la Liga MX, así lo ve Ricardo La Volpe.El ex técnico de la Selección Mexicana en el Mundial de Alemania 2006 elogió la forma de juego del chiverío, que marcha como líder de la tabla con seis victor…

Las Chivas de Gabriel Milito es uno de los mejores equipos en la Liga MX, así lo ve Ricardo La Volpe.
El ex técnico de la Selección Mexicana en el Mundial de Alemania 2006 elogió la forma de juego d… [+1508 chars]', 476, 'radiocinconoticias', 'Política', '2026-02-18T23:06:00Z', 'Alonso González', 0, 'https://cdn.milenio.com/uploads/media/2026/02/18/ricardo-volpe-ve-chivas-mejores.jpg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.motorpasion.com.mx/industria/estados-unidos-cambia-su-ley-mete-aprietos-a-muchas-marcas-autos-mes-prohibira-autos-microchips-software-chino', 'https://www.motorpasion.com.mx/industria/estados-unidos-cambia-su-ley-mete-aprietos-a-muchas-marcas-autos-mes-prohibira-autos-microchips-software-chino', 'Estados Unidos cambia su ley y mete en aprietos a muchas marcas de autos: en un mes prohibirá los autos con microchips o software chino', 'Dentro de toda la guerra comercial que estamos viviendo, se había perdido de vista un ataque por parte de la administración de Joe Biden, el cual surgirá efecto en menos de un mes, cuando se prohiba la venta de automóviles con software chino dentro de los Est…

Dentro de toda la guerra comercial que...', 'https://i.blogs.es/2c3c33/autos-prohibidos-estados-unidos/840_560.jpeg', '2026-02-18T23:00:57Z', 'Dentro de toda la guerra comercial que estamos viviendo, se había perdido de vista un ataque por parte de la administración de Joe Biden, el cual surgirá efecto en menos de un mes, cuando se prohiba la venta de automóviles con software chino dentro de los Est…

Dentro de toda la guerra comercial que estamos viviendo, se había perdido de vista un ataque por parte de la administración de Joe Biden, el cual surgirá efecto en menos de un mes, cuando se prohiba … [+2173 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.motorpasion.com.mx/industria/estados-unidos-cambia-su-ley-mete-aprietos-a-muchas-marcas-autos-mes-prohibira-autos-microchips-software-chino', 'Estados Unidos cambia su ley y mete en aprietos a muchas marcas de autos: en un mes prohibirá los autos con microchips o software chino', 'Dentro de toda la guerra comercial que estamos viviendo, se había perdido de vista un ataque por parte de la administración de Joe Biden, el cual surgirá efecto en menos de un mes, cuando se prohiba la venta de automóviles con software chino dentro de los Est…

Dentro de toda la guerra comercial que...', 'Dentro de toda la guerra comercial que estamos viviendo, se había perdido de vista un ataque por parte de la administración de Joe Biden, el cual surgirá efecto en menos de un mes, cuando se prohiba la venta de automóviles con software chino dentro de los Est…

Dentro de toda la guerra comercial que estamos viviendo, se había perdido de vista un ataque por parte de la administración de Joe Biden, el cual surgirá efecto en menos de un mes, cuando se prohiba … [+2173 chars]', 476, 'reportecentralmx', 'Tecnología', '2026-02-18T23:00:57Z', 'Alonso Brugada', 0, 'https://i.blogs.es/2c3c33/autos-prohibidos-estados-unidos/840_560.jpeg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.xataka.com.mx/home/ventanas-abiertas-cerradas-esto-recomiendan-expertos-para-mantener-fresco-tu-hogar', 'https://www.xataka.com.mx/home/ventanas-abiertas-cerradas-esto-recomiendan-expertos-para-mantener-fresco-tu-hogar', 'Abría mis ventanas en épocas de calor, pero descubrí que es un error. Esto dicen los expertos', 'Las temperaturas por fin comienzan a subir en todo el país. Los team calor lo celebran y los team frío lo sufren. La verdad, a final de cuentas, es que ahora sudarás todo el día de partes que ni siquiera considerabas, además de que tendrás más sed y probablem…

Las temperaturas por fin comienzan a s...', 'https://i.blogs.es/c9113d/calor-ventanas-mexico-recomendacion/840_560.jpeg', '2026-02-18T23:00:57Z', 'Las temperaturas por fin comienzan a subir en todo el país. Los team calor lo celebran y los team frío lo sufren. La verdad, a final de cuentas, es que ahora sudarás todo el día de partes que ni siquiera considerabas, además de que tendrás más sed y probablem…

Las temperaturas por fin comienzan a subir en todo el país. Los team calor lo celebran y los team frío lo sufren. La verdad, a final de cuentas, es que ahora sudarás todo el día de partes que ni siqu… [+3840 chars]', 'Cultura'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.xataka.com.mx/home/ventanas-abiertas-cerradas-esto-recomiendan-expertos-para-mantener-fresco-tu-hogar', 'Abría mis ventanas en épocas de calor, pero descubrí que es un error. Esto dicen los expertos', 'Las temperaturas por fin comienzan a subir en todo el país. Los team calor lo celebran y los team frío lo sufren. La verdad, a final de cuentas, es que ahora sudarás todo el día de partes que ni siquiera considerabas, además de que tendrás más sed y probablem…

Las temperaturas por fin comienzan a s...', 'Las temperaturas por fin comienzan a subir en todo el país. Los team calor lo celebran y los team frío lo sufren. La verdad, a final de cuentas, es que ahora sudarás todo el día de partes que ni siquiera considerabas, además de que tendrás más sed y probablem…

Las temperaturas por fin comienzan a subir en todo el país. Los team calor lo celebran y los team frío lo sufren. La verdad, a final de cuentas, es que ahora sudarás todo el día de partes que ni siqu… [+3840 chars]', 476, 'tvmexico', 'Cultura', '2026-02-18T23:00:57Z', 'Eric Ramirez', 0, 'https://i.blogs.es/c9113d/calor-ventanas-mexico-recomendacion/840_560.jpeg'
);

INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (
  'https://www.puntodebreak.com/2026/02/19/gira-latinoamericana-tierra-no-jugara-cemento-ahora', 'https://www.puntodebreak.com/2026/02/19/gira-latinoamericana-tierra-no-jugara-cemento-ahora', 'Toda la gira latinoamericana de tierra no se jugará sobre cemento... por ahora', 'En el día de ayer salió la información de que esta gira (Buenos Aires, Rio, Santiago) pasará a jugarse sobre cemento en 2028. Eso no es cierto... por ahora.

Ayer, desde Sudamérica, se contó en diversos medios y a través de distintos periodistas que la gira latinoamericana de tenis sobre tierra bati...', 'https://www.puntodebreak.com/sites/default/files/styles/epsa_detail_thumbail/public/2026-02/rio-open-gira-sudamerica.jpg?h=920929c4&itok=83ESO2Df', '2026-02-18T23:00:49Z', 'En el día de ayer salió la información de que esta gira (Buenos Aires, Rio, Santiago) pasará a jugarse sobre cemento en 2028. Eso no es cierto... por ahora.

Ayer, desde Sudamérica, se contó en diversos medios y a través de distintos periodistas que la gira latinoamericana de tenis sobre tierra batida pasaría a jugarse sobre cemento a partir de 2028. Real… [+5841 chars]', 'Tecnología'
);
INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (
  '1', 'https://www.puntodebreak.com/2026/02/19/gira-latinoamericana-tierra-no-jugara-cemento-ahora', 'Toda la gira latinoamericana de tierra no se jugará sobre cemento... por ahora', 'En el día de ayer salió la información de que esta gira (Buenos Aires, Rio, Santiago) pasará a jugarse sobre cemento en 2028. Eso no es cierto... por ahora.

Ayer, desde Sudamérica, se contó en diversos medios y a través de distintos periodistas que la gira latinoamericana de tenis sobre tierra bati...', 'En el día de ayer salió la información de que esta gira (Buenos Aires, Rio, Santiago) pasará a jugarse sobre cemento en 2028. Eso no es cierto... por ahora.

Ayer, desde Sudamérica, se contó en diversos medios y a través de distintos periodistas que la gira latinoamericana de tenis sobre tierra batida pasaría a jugarse sobre cemento a partir de 2028. Real… [+5841 chars]', 372, 'verticenoticias', 'Tecnología', '2026-02-18T23:00:49Z', 'Jose Morón', 0, 'https://www.puntodebreak.com/sites/default/files/styles/epsa_detail_thumbail/public/2026-02/rio-open-gira-sudamerica.jpg?h=920929c4&itok=83ESO2Df'
);
