#!/usr/bin/env python3
"""
Seed the D1 database with articles from the JSON data file.
Generates a SQL file and runs it against the remote D1 database.
"""
import json
import uuid
import re
import os
import subprocess

SITES = [
    'bitacoraurbana', 'cbnnoticias', 'centralmexico', 'mexicoinformado',
    'nodoinformativo', 'noticiasobjetivo', 'radiocinconoticias',
    'reportecentralmx', 'tvmexico', 'verticenoticias'
]

CATEGORIES = ['Nacional', 'Internacional', 'Política', 'Economía', 'Tecnología', 'Deportes', 'Cultura', 'Sociedad']

def slugify(text):
    text = text.lower().strip()
    text = re.sub(r'[áàäâ]', 'a', text)
    text = re.sub(r'[éèëê]', 'e', text)
    text = re.sub(r'[íìïî]', 'i', text)
    text = re.sub(r'[óòöô]', 'o', text)
    text = re.sub(r'[úùüû]', 'u', text)
    text = re.sub(r'[ñ]', 'n', text)
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    text = re.sub(r'^-+|-+$', '', text)
    return text[:80]

def esc(s):
    """Escape single quotes for SQL."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"

def guess_category(title, description):
    title_lower = (title or '').lower()
    desc_lower = (description or '').lower()
    text = title_lower + ' ' + desc_lower
    if any(w in text for w in ['economía', 'economia', 'finanzas', 'peso', 'dólar', 'inflación', 'pib', 'banco']):
        return 'Economía'
    if any(w in text for w in ['política', 'politica', 'presidente', 'gobierno', 'congreso', 'senado', 'diputado', 'elección']):
        return 'Política'
    if any(w in text for w in ['tecnología', 'tecnologia', 'ia', 'inteligencia artificial', 'digital', 'internet', 'app']):
        return 'Tecnología'
    if any(w in text for w in ['deporte', 'fútbol', 'futbol', 'liga', 'mundial', 'olimp']):
        return 'Deportes'
    if any(w in text for w in ['cultura', 'arte', 'música', 'musica', 'cine', 'teatro', 'libro']):
        return 'Cultura'
    if any(w in text for w in ['internacional', 'eeuu', 'estados unidos', 'europa', 'china', 'rusia', 'trump']):
        return 'Internacional'
    return 'Nacional'

# Load data
data = json.load(open('data/noticias_paraphrased_20260219_045326.json'))
print(f'Loaded {len(data)} articles')

sql_lines = []
sql_lines.append('-- Seed data for ARTICULOS_ORIGINALES and ARTICULOS_PARAFRASEADOS')
sql_lines.append('-- Generated by seed_db.py')
sql_lines.append('')

# Also add URL_IMAGEN column to ARTICULOS_PARAFRASEADOS if not exists
sql_lines.append('-- Add URL_IMAGEN column if not exists (safe to run multiple times)')
sql_lines.append('ALTER TABLE ARTICULOS_PARAFRASEADOS ADD COLUMN URL_IMAGEN TEXT;')
sql_lines.append('')

for i, art in enumerate(data):
    orig_id = art.get('original_article_id') or str(uuid.uuid4())
    para_id = art.get('variation_id') or str(uuid.uuid4())
    
    title = art.get('title') or art.get('original_title') or 'Sin título'
    orig_title = art.get('original_title') or title
    description = art.get('description') or ''
    content = art.get('full_text') or art.get('content') or description
    url = art.get('url') or ''
    image_url = art.get('urlToImage') or ''
    published_at = art.get('publishedAt') or '2026-02-19T00:00:00Z'
    author = art.get('author') or 'Redacción'
    category = guess_category(title, description)
    
    # Assign to a site (round-robin)
    site = SITES[i % len(SITES)]
    
    # Insert into ARTICULOS_ORIGINALES
    sql_lines.append(f'INSERT OR IGNORE INTO ARTICULOS_ORIGINALES (ID, URL, TITULO, DESCRIPCION, URL_IMAGEN, FECHA, CONTENIDO, CATEGORIA) VALUES (')
    sql_lines.append(f'  {esc(orig_id)}, {esc(url)}, {esc(orig_title)}, {esc(description)}, {esc(image_url)}, {esc(published_at)}, {esc(content[:5000])}, {esc(category)}')
    sql_lines.append(');')
    
    # Insert into ARTICULOS_PARAFRASEADOS
    sql_lines.append(f'INSERT OR IGNORE INTO ARTICULOS_PARAFRASEADOS (ID, ID_ARTICULO_ORIGINAL, TITULO_PARAFRASEADO, DESCRIPCION_PARAFRASEADA, CONTENIDO, LONGITUD, SITIO_DESTINO, CATEGORIA, FECHA_PUBLICACION, AUTOR, DESTACADO, URL_IMAGEN) VALUES (')
    sql_lines.append(f'  {esc(para_id)}, {esc(orig_id)}, {esc(title)}, {esc(description)}, {esc(content[:5000])}, {len(content)}, {esc(site)}, {esc(category)}, {esc(published_at)}, {esc(author)}, {1 if i < 3 else 0}, {esc(image_url)}')
    sql_lines.append(');')
    sql_lines.append('')

sql_content = '\n'.join(sql_lines)

# Write SQL file
sql_file = 'seed_articles.sql'
with open(sql_file, 'w', encoding='utf-8') as f:
    f.write(sql_content)

print(f'SQL file written: {sql_file}')
print(f'Running against D1 database...')

# Run against D1
db_id = '039ec6ab-8f14-4e79-8f02-021df67a6c18'
# Use absolute path for the SQL file
abs_sql = os.path.abspath(sql_file)
result = subprocess.run(
    ['npx', 'wrangler', 'd1', 'execute', 'news_db', '--remote', f'--file={abs_sql}'],
    cwd='src',
    capture_output=True,
    text=True
)

print('STDOUT:', result.stdout[-2000:] if result.stdout else '(empty)')
print('STDERR:', result.stderr[-2000:] if result.stderr else '(empty)')
print('Return code:', result.returncode)
