// Generates index.html, articulo/index.html, categoria/*.html
var { CATEGORIES, CAT_LABELS, API_BASE } = require('./config');

function genIndexHTML(site) {
    var h = '';
    h += '<!DOCTYPE html>\n<html lang="es">\n<head>\n';
    h += '    <meta charset="utf-8"/>\n';
    h += '    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n';
    h += '    <title>' + site.name + ' - Noticias en Tiempo Real</title>\n';
    h += '    <meta content="' + site.name + ' - Noticias digitales en tiempo real." name="description"/>\n';
    h += '    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n';
    h += '    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n';
    h += '    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet"/>\n';
    h += '    <link href="style.css" rel="stylesheet"/>\n';
    h += '    <link href="style-custom.css" rel="stylesheet"/>\n';
    h += '    <link rel="alternate" type="application/rss+xml" title="' + site.name + ' RSS" href="/rss.xml"/>\n';
    h += '</head>\n<body>\n\n';
    h += '<div id="site-preloader"></div>\n<div id="site-header"></div>\n\n';
    h += '<main class="main-content">\n    <div class="container">\n';
    h += '        <section class="featured-section">\n';
    h += '            <div id="featured-container">\n';
    h += '                <div style="text-align:center;padding:60px;color:var(--primary-color);">Cargando noticias...</div>\n';
    h += '            </div>\n        </section>\n';
    h += '        <section class="news-section" id="news-section">\n';
    h += '            <h2 class="section-title">Mas Noticias</h2>\n';
    h += '            <div id="news-container" class="card-grid"></div>\n';
    h += '        </section>\n    </div>\n</main>\n\n';
    h += '<div id="site-footer"></div>\n\n';
    h += '<script src="components.js"></script>\n<script src="script.js"></script>\n';
    h += '<script>\n';
    h += getIndexScript(site);
    h += '</script>\n\n</body>\n</html>';
    return h;
}

function getIndexScript(site) {
    var s = '';
    s += '(function() {\n';
    s += "    var API = '" + API_BASE + "/api/articles?site=" + site.slug + "&limit=20';\n\n";
    s += '    async function loadArticles() {\n';
    s += '        try {\n';
    s += '            var res = await fetch(API);\n';
    s += "            if (!res.ok) throw new Error('Network error');\n";
    s += '            var data = await res.json();\n';
    s += '            var articles = data.articles;\n';
    s += '            if (!articles || !articles.length) {\n';
    s += "                document.getElementById('featured-container').innerHTML = '<div style=\"text-align:center;padding:60px;\">No hay noticias disponibles.</div>';\n";
    s += '                return;\n            }\n';
    s += '            renderSidebar(articles.slice(0, 6));\n';
    s += '            renderGrid(articles.slice(6));\n';
    s += '        } catch(e) {\n';
    s += "            console.error('Error:', e);\n";
    s += "            document.getElementById('featured-container').innerHTML = '<div style=\"text-align:center;padding:60px;\">Error al cargar noticias.</div>';\n";
    s += '        }\n    }\n\n';
    s += '    function renderSidebar(articles) {\n';
    s += "        var container = document.getElementById('featured-container');\n";
    s += '        if (!container || !articles.length) return;\n';
    s += '        var main = articles[0], list = articles.slice(1, 6);\n';
    s += '        var listHtml = list.map(function(a) {\n';
    s += "            return '<div class=\"rc-list-item\">' +\n";
    s += "                '<a href=\"articulo/index.html?slug=' + enc(a.slug) + '\">' +\n";
    s += "                '<img src=\"' + (a.imageUrl || 'logo.png') + '\" alt=\"' + esc(a.title) + '\" loading=\"lazy\"></a>' +\n";
    s += "                '<div class=\"rc-list-content\">' +\n";
    s += "                '<span class=\"category-badge cat-' + esc((a.category||'general').toLowerCase()) + '\">' + esc(a.category||'General') + '</span>' +\n";
    s += "                '<h4><a href=\"articulo/index.html?slug=' + enc(a.slug) + '\">' + esc(a.title) + '</a></h4>' +\n";
    s += "                '<div class=\"card-meta\"><span><i class=\"far fa-calendar\"></i> ' + fmtDate(a.publishedAt) + '</span></div>' +\n";
    s += "                '</div></div>';\n";
    s += '        }).join("");\n\n';
    s += "        container.innerHTML = '<div class=\"sidebar-layout\">' +\n";
    s += "            '<article class=\"rc-main-article\">' +\n";
    s += "            '<div class=\"main-img-wrapper\"><a href=\"articulo/index.html?slug=' + enc(main.slug) + '\">' +\n";
    s += "            '<img src=\"' + (main.imageUrl || 'logo.png') + '\" alt=\"' + esc(main.title) + '\" loading=\"lazy\"></a></div>' +\n";
    s += "            '<div class=\"main-content-body\">' +\n";
    s += "            '<span class=\"category-badge cat-' + esc((main.category||'general').toLowerCase()) + '\">' + esc(main.category||'General') + '</span>' +\n";
    s += "            '<h2><a href=\"articulo/index.html?slug=' + enc(main.slug) + '\">' + esc(main.title) + '</a></h2>' +\n";
    s += "            '<p>' + esc(main.excerpt||'') + '</p>' +\n";
    s += "            '<div class=\"main-meta\">' +\n";
    s += "            '<span><i class=\"far fa-user\"></i> ' + esc(main.author||'Redaccion') + '</span>' +\n";
    s += "            '<span><i class=\"far fa-calendar\"></i> ' + fmtDate(main.publishedAt) + '</span></div>' +\n";
    s += "            '<a href=\"articulo/index.html?slug=' + enc(main.slug) + '\" class=\"rc-read-more\">Leer mas <i class=\"fas fa-arrow-right\"></i></a>' +\n";
    s += "            '</div></article>' +\n";
    s += "            '<aside class=\"rc-sidebar-list\">' +\n";
    s += "            '<div class=\"rc-sidebar-header\"><h3><i class=\"fas fa-fire\"></i> &nbsp;Mas Leidas</h3></div>' +\n";
    s += "            listHtml + '</aside></div>';\n";
    s += '    }\n\n';
    s += '    function renderGrid(articles) {\n';
    s += "        var container = document.getElementById('news-container');\n";
    s += "        var section = document.getElementById('news-section');\n";
    s += '        if (!container) return;\n';
    s += "        if (!articles.length) { if (section) section.style.display = 'none'; return; }\n";
    s += '        container.innerHTML = articles.map(function(a) {\n';
    s += "            return '<article class=\"article-card\">' +\n";
    s += "                '<div class=\"card-image-wrapper\"><a href=\"articulo/index.html?slug=' + enc(a.slug) + '\">' +\n";
    s += "                '<img src=\"' + (a.imageUrl || 'logo.png') + '\" alt=\"' + esc(a.title) + '\" loading=\"lazy\"></a></div>' +\n";
    s += "                '<div class=\"card-content\">' +\n";
    s += "                '<span class=\"card-category-badge cat-' + esc((a.category||'general').toLowerCase()) + '\">' + esc(a.category||'General') + '</span>' +\n";
    s += "                '<h3 class=\"card-title\"><a href=\"articulo/index.html?slug=' + enc(a.slug) + '\">' + esc(a.title) + '</a></h3>' +\n";
    s += "                '<p class=\"card-excerpt\">' + esc(a.excerpt||'') + '</p>' +\n";
    s += "                '<div class=\"card-footer\">' +\n";
    s += "                '<span class=\"card-author\"><i class=\"far fa-user\"></i> ' + esc(a.author||'Redaccion') + '</span>' +\n";
    s += "                '<span class=\"card-date\"><i class=\"far fa-calendar\"></i> ' + fmtDate(a.publishedAt) + '</span>' +\n";
    s += "                '</div></div></article>';\n";
    s += '        }).join("");\n    }\n\n';
    s += "    function esc(t) { if (!t) return ''; return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'); }\n";
    s += "    function enc(t) { return encodeURIComponent(t || ''); }\n";
    s += "    function fmtDate(d) { return d ? new Date(d).toLocaleDateString('es-MX') : ''; }\n\n";
    s += "    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', loadArticles);\n";
    s += '    else loadArticles();\n';
    s += '})();\n';
    return s;
}

function genArticuloHTML(site) {
    var h = '';
    h += '<!DOCTYPE html>\n<html lang="es">\n<head>\n';
    h += '    <meta charset="UTF-8">\n';
    h += '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
    h += '    <title id="page-title">Cargando... - ' + site.name + '</title>\n';
    h += '    <meta name="description" id="page-desc" content="">\n';
    h += '    <link rel="preconnect" href="https://fonts.googleapis.com">\n';
    h += '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n';
    h += '    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">\n';
    h += '    <link rel="stylesheet" href="../style.css">\n';
    h += '    <link rel="stylesheet" href="../article.css">\n';
    h += '    <link rel="stylesheet" href="../style-custom.css">\n';
    h += '</head>\n<body>\n';
    h += '    <div id="site-preloader"></div>\n';
    h += '    <div id="site-header"></div>\n\n';
    h += '    <main class="main-content article-page">\n        <div class="container">\n';
    h += '            <div id="article-loading" style="text-align:center;padding:60px 20px;"><p>Cargando articulo...</p></div>\n';
    h += '            <div id="article-error" style="display:none;text-align:center;padding:60px 20px;">\n';
    h += '                <h2>Articulo no encontrado</h2>\n';
    h += '                <p style="color:#666;margin:20px 0;">El articulo que buscas no esta disponible.</p>\n';
    h += '                <a href="../index.html" style="color:var(--primary-color);font-weight:bold;"><i class="fas fa-arrow-left"></i> Volver al inicio</a>\n';
    h += '            </div>\n';
    h += '            <article id="article-content" class="article-full" style="display:none;">\n';
    h += '                <div class="article-header">\n';
    h += '                    <div class="breadcrumb" style="margin-bottom:12px;"><a href="../index.html">Inicio</a> <span style="margin:0 6px;color:#999;">/</span> <span id="art-category-breadcrumb"></span></div>\n';
    h += '                    <span id="art-category-badge" class="article-category-badge"></span>\n';
    h += '                    <h1 id="art-title" class="article-title"></h1>\n';
    h += '                    <div class="article-meta">\n';
    h += '                        <span class="author"><i class="far fa-user"></i> Por <span id="art-author"></span></span>\n';
    h += '                        <span class="separator">&#8226;</span>\n';
    h += '                        <span class="date"><i class="far fa-calendar"></i> <span id="art-date"></span></span>\n';
    h += '                    </div>\n                </div>\n';
    h += '                <div class="article-image-wrapper" id="art-image-wrapper">\n';
    h += '                    <img id="art-image" class="article-image" src="" alt="" loading="lazy" style="width:100%;max-height:500px;object-fit:cover;border-radius:8px;margin:20px 0;">\n';
    h += '                </div>\n';
    h += '                <div id="art-body" class="article-content"></div>\n';
    h += '                <div class="article-footer" style="margin-top:30px;padding-top:20px;border-top:1px solid #eee;">\n';
    h += '                    <div class="article-share">\n';
    h += '                        <span style="font-weight:bold;margin-right:10px;">Compartir:</span>\n';
    h += '                        <a id="share-fb" href="#" target="_blank" rel="noopener" style="margin-right:8px;"><i class="fab fa-facebook-f"></i></a>\n';
    h += '                        <a id="share-tw" href="#" target="_blank" rel="noopener" style="margin-right:8px;"><i class="fab fa-twitter"></i></a>\n';
    h += '                        <a id="share-wa" href="#" target="_blank" rel="noopener"><i class="fab fa-whatsapp"></i></a>\n';
    h += '                    </div>\n                </div>\n';
    h += '                <div style="margin-top:30px;"><a href="../index.html" class="back-link"><i class="fas fa-arrow-left"></i> Volver al inicio</a></div>\n';
    h += '            </article>\n        </div>\n    </main>\n\n';
    h += '    <div id="site-footer"></div>\n\n';
    h += '    <script src="../script.js"></script>\n';
    h += '    <script src="../components.js"></script>\n';
    h += '    <script>\n';
    h += getArticleScript(site);
    h += '    </script>\n</body>\n</html>';
    return h;
}

function getArticleScript(site) {
    var s = '';
    s += '    (async function() {\n';
    s += "        var params = new URLSearchParams(location.search);\n";
    s += "        var slug = params.get('slug');\n";
    s += '        if (!slug) { showError(); return; }\n';
    s += '        try {\n';
    s += "            var res = await fetch('" + API_BASE + "/api/articles/' + encodeURIComponent(slug));\n";
    s += "            if (!res.ok) throw new Error('not found');\n";
    s += '            var data = await res.json(); var a = data.article;\n';
    s += "            if (!a) throw new Error('empty');\n";
    s += '            renderArticle(a);\n';
    s += '        } catch(e) { showError(); }\n\n';
    s += '        function renderArticle(a) {\n';
    s += "            document.title = (a.title || 'Articulo') + ' - " + site.name + "';\n";
    s += "            var d=document.getElementById('page-desc'); if(d) d.content=a.excerpt||'';\n";
    s += "            var cat=a.category||'',cs=cat.toLowerCase().replace(/\\s+/g,'-');\n";
    s += "            var b=document.getElementById('art-category-badge'); if(b){b.textContent=cat;b.className='article-category-badge cat-'+cs;}\n";
    s += "            var bc=document.getElementById('art-category-breadcrumb'); if(bc) bc.textContent=cat;\n";
    s += "            var t=document.getElementById('art-title'); if(t) t.textContent=a.title||'';\n";
    s += "            var au=document.getElementById('art-author'); if(au) au.textContent=a.author||'Redaccion';\n";
    s += "            var dt=document.getElementById('art-date'); if(dt) dt.textContent=a.publishedAt?new Date(a.publishedAt).toLocaleDateString('es-MX',{year:'numeric',month:'long',day:'numeric'}):'';\n";
    s += "            var iw=document.getElementById('art-image-wrapper'),im=document.getElementById('art-image');\n";
    s += "            if(a.imageUrl&&im){im.src=a.imageUrl;im.alt=a.title||'';}else if(iw)iw.style.display='none';\n";
    s += "            var body=document.getElementById('art-body');\n";
    s += "            if(body){var c=a.content||'';if(!c)c='<p>'+(a.excerpt||'')+'</p>';else if(!c.includes('<p>')&&!c.includes('<div>'))c=c.split(/\\n\\n+/).map(function(p){return'<p>'+p.trim()+'</p>';}).join('');body.innerHTML=c;}\n";
    s += "            var url=encodeURIComponent(location.href),txt=encodeURIComponent(a.title||'');\n";
    s += "            var fb=document.getElementById('share-fb'),tw=document.getElementById('share-tw'),wa=document.getElementById('share-wa');\n";
    s += "            if(fb)fb.href='https://www.facebook.com/sharer/sharer.php?u='+url;\n";
    s += "            if(tw)tw.href='https://twitter.com/intent/tweet?url='+url+'&text='+txt;\n";
    s += "            if(wa)wa.href='https://wa.me/?text='+txt+'%20'+url;\n";
    s += "            document.getElementById('article-loading').style.display='none';\n";
    s += "            document.getElementById('article-content').style.display='block';\n";
    s += '        }\n';
    s += '        function showError() {\n';
    s += "            document.getElementById('article-loading').style.display='none';\n";
    s += "            document.getElementById('article-error').style.display='block';\n";
    s += '        }\n';
    s += '    })();\n';
    return s;
}

function genCategoriaHTML(site, cat) {
    var label = CAT_LABELS[cat] || cat;
    var h = '';
    h += '<!DOCTYPE html>\n<html lang="es">\n<head>\n';
    h += '    <meta charset="UTF-8">\n';
    h += '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
    h += '    <title>' + label + ' - ' + site.name + '</title>\n';
    h += '    <meta name="description" content="Noticias de ' + label + ' en ' + site.name + '.">\n';
    h += '    <link rel="preconnect" href="https://fonts.googleapis.com">\n';
    h += '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n';
    h += '    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">\n';
    h += '    <link rel="stylesheet" href="../style.css">\n';
    h += '    <link rel="stylesheet" href="../style-custom.css">\n';
    h += '</head>\n<body>\n';
    h += '    <div id="site-preloader"></div>\n';
    h += '    <div id="site-header"></div>\n\n';
    h += '    <main class="main-content">\n        <div class="container">\n';
    h += '            <div class="category-header" style="margin:30px 0 20px;">\n';
    h += '                <span class="category-badge cat-' + cat + '">' + label + '</span>\n';
    h += '                <h1 class="section-title" style="text-align:left;margin:10px 0 6px;">Noticias de ' + label + '</h1>\n';
    h += '                <p style="color:var(--text-muted);font-size:0.95rem;">Todas las noticias actualizadas sobre ' + label + '.</p>\n';
    h += '            </div>\n';
    h += '            <div id="cat-loading" style="text-align:center;padding:40px;"><p>Cargando noticias...</p></div>\n';
    h += '            <div id="cat-empty" style="display:none;text-align:center;padding:40px;">\n';
    h += '                <p>No hay noticias disponibles en esta categoria.</p>\n';
    h += '                <a href="../index.html" style="color:var(--primary-color);font-weight:bold;">Volver al inicio</a>\n';
    h += '            </div>\n';
    h += '            <div id="cat-grid" class="card-grid" style="display:none;margin-bottom:60px;"></div>\n';
    h += '        </div>\n    </main>\n\n';
    h += '    <div id="site-footer"></div>\n\n';
    h += '    <script src="../script.js"></script>\n';
    h += '    <script src="../components.js"></script>\n';
    h += '    <script>\n';
    h += getCategoryScript(site, cat, label);
    h += '    </script>\n</body>\n</html>';
    return h;
}

function getCategoryScript(site, cat, label) {
    var s = '';
    s += '    (async function() {\n';
    s += '        try {\n';
    s += "            var res = await fetch('" + API_BASE + "/api/articles?site=" + site.slug + "&category=" + cat + "&limit=30');\n";
    s += "            if (!res.ok) throw new Error('fetch error');\n";
    s += '            var data = await res.json(); var articles = data.articles;\n';
    s += '            if (!articles || !articles.length) { hide(); return; }\n';
    s += "            var grid = document.getElementById('cat-grid');\n";
    s += '            grid.innerHTML = articles.map(renderCard).join("");\n';
    s += "            document.getElementById('cat-loading').style.display='none';\n";
    s += "            grid.style.display='';\n";
    s += '        } catch(e) { hide(); }\n\n';
    s += '        function hide() {\n';
    s += "            document.getElementById('cat-loading').style.display='none';\n";
    s += "            document.getElementById('cat-empty').style.display='block';\n";
    s += '        }\n';
    s += '        function renderCard(a) {\n';
    s += "            var s=a.slug||'',img=a.imageUrl||'../logo.png',c=a.category||'" + label + "';\n";
    s += "            var cs=c.toLowerCase().replace(/\\s+/g,'-'),t=esc(a.title||''),ex=esc(a.excerpt||'');\n";
    s += "            var au=esc(a.author||'Redaccion'),d=a.publishedAt?new Date(a.publishedAt).toLocaleDateString('es-MX'):'';\n";
    s += "            var u='../articulo/index.html?slug='+encodeURIComponent(s);\n";
    s += "            return '<article class=\"article-card\"><div class=\"card-image-wrapper\"><a href=\"'+u+'\"><img src=\"'+img+'\" alt=\"'+t+'\" loading=\"lazy\"></a><span class=\"card-category-badge cat-'+cs+'\">'+c+'</span></div><div class=\"card-content\"><h3 class=\"card-title\"><a href=\"'+u+'\">'+t+'</a></h3><p class=\"card-excerpt\">'+ex+'</p><div class=\"card-footer\"><span class=\"card-author\">Por '+au+'</span><span class=\"card-date\">'+d+'</span></div></div></article>';\n";
    s += '        }\n';
    s += "        function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n";
    s += '    })();\n';
    return s;
}

module.exports = { genIndexHTML, genArticuloHTML, genCategoriaHTML };
