-- Migration: Add Facebook columns to ARTICULOS_PARAFRASEADOS
-- Date: 2026-03-13
-- Issue: Facebook publishing failed because columns were missing from table

-- Add Facebook tracking columns to ARTICULOS_PARAFRASEADOS
ALTER TABLE ARTICULOS_PARAFRASEADOS ADD COLUMN FB_REQUERIDO INTEGER DEFAULT 0;
ALTER TABLE ARTICULOS_PARAFRASEADOS ADD COLUMN FB_PUBLICADO INTEGER DEFAULT 0;
ALTER TABLE ARTICULOS_PARAFRASEADOS ADD COLUMN FB_FECHA TEXT;
ALTER TABLE ARTICULOS_PARAFRASEADOS ADD COLUMN FB_SITIOS_PUBLICADOS TEXT DEFAULT '';

-- Verify columns were added
SELECT sql FROM sqlite_master WHERE type='table' AND name='ARTICULOS_PARAFRASEADOS';
