-- Script para corregir artículos con FB_PUBLICADO = 1 pero con sitios pendientes
-- Ejecutar: wrangler d1 execute news_db --file fix_fb_publicado.sql --remote

-- Actualizar ARTICULOS_PARAFRASEADOS: establecer FB_PUBLICADO = 0 si hay sitios pendientes
UPDATE ARTICULOS_PARAFRASEADOS
SET FB_PUBLICADO = 0
WHERE FB_PUBLICADO = 1
  AND FB_SITIOS_PUBLICADOS != ''
  AND FB_SITIOS_PUBLICADOS != SITIO_DESTINO
  AND (
    -- Verificar que FB_SITIOS_PUBLICADOS tenga menos sitios que SITIO_DESTINO
    LENGTH(FB_SITIOS_PUBLICADOS) - LENGTH(REPLACE(FB_SITIOS_PUBLICADOS, ',', '')) <
    LENGTH(SITIO_DESTINO) - LENGTH(REPLACE(SITIO_DESTINO, ',', ''))
  );

-- Actualizar ARTICULOS_CMS: establecer FB_PUBLICADO = 0 si hay sitios pendientes
UPDATE ARTICULOS_CMS
SET FB_PUBLICADO = 0
WHERE FB_PUBLICADO = 1
  AND FB_SITIOS_PUBLICADOS != ''
  AND FB_SITIOS_PUBLICADOS != SITIOS_DESTINO
  AND (
    -- Verificar que FB_SITIOS_PUBLICADOS tenga menos sitios que SITIOS_DESTINO
    LENGTH(FB_SITIOS_PUBLICADOS) - LENGTH(REPLACE(FB_SITIOS_PUBLICADOS, ',', '')) <
    LENGTH(SITIOS_DESTINO) - LENGTH(REPLACE(SITIOS_DESTINO, ',', ''))
  );

-- Verificar resultados
SELECT 
  'ARTICULOS_PARAFRASEADOS' as tabla,
  COUNT(*) as total,
  SUM(CASE WHEN FB_PUBLICADO = 0 THEN 1 ELSE 0 END) as pendientes,
  SUM(CASE WHEN FB_PUBLICADO = 1 THEN 1 ELSE 0 END) as publicados
FROM ARTICULOS_PARAFRASEADOS
WHERE FB_REQUERIDO = 1
UNION ALL
SELECT 
  'ARTICULOS_CMS' as tabla,
  COUNT(*) as total,
  SUM(CASE WHEN FB_PUBLICADO = 0 THEN 1 ELSE 0 END) as pendientes,
  SUM(CASE WHEN FB_PUBLICADO = 1 THEN 1 ELSE 0 END) as publicados
FROM ARTICULOS_CMS
WHERE FB_REQUERIDO = 1 OR ESTADO = 'PUBLICADO';
