-- Actualizar la tabla SITIOS con los secrets correctos de Cloudflare
-- y activar Facebook para todos los sitios nuevos

-- Sitios Estables (10) - Actualizar secrets
UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_RADIOCINCONOTICIAS',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'radiocinconoticias';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_CENTRALMEXICO',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'centralmexico';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_TVMEXICO',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'tvmexico';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_CBNNOTICIAS',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'cbnnoticias';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_MEXICOINFORMADO',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'mexicoinformado';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_NODOINFORMATIVO',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'nodoinformativo';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_BITACORAURBANA',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'bitacoraurbana';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_REPORTECENTRALMX',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'reportecentralmx';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_VERTICENOTICIAS',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'verticenoticias';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_NOTICIASOBJETIVO',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'noticiasobjetivo';

-- Nuevos Sitios (17) - Actualizar secrets y activar
UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_BOOMINFORMATIVO',
    FACEBOOK_PAGE_ID = '501728116348917',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'boominformativo';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_CAPITALPRESS',
    FACEBOOK_PAGE_ID = '458242550714232',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'capitalpress';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_DIARIOEXPRESS',
    FACEBOOK_PAGE_ID = '270142869517794',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'diarioexpress';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_ELPULSOMEXICANO',
    FACEBOOK_PAGE_ID = '253187761218980',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'elpulsomexicano';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_ENFOQUECAPITAL',
    FACEBOOK_PAGE_ID = '457328060805587',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'enfoquecapital';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_ENFOQUEDIRECTO',
    FACEBOOK_PAGE_ID = '454841367704076',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'enfoquedirecto';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_FORMULACDMX',
    FACEBOOK_PAGE_ID = '500033023189155',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'formulacdmx';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_MEXICANTIMES',
    FACEBOOK_PAGE_ID = '578088192045850',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'mexicantimes';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_MEXICO360NOTICIAS',
    FACEBOOK_PAGE_ID = '286495644543503',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'mexico360noticias';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_MRADIO',
    FACEBOOK_PAGE_ID = '472254365974557',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'mradio';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_NOTICIASHORIZONTE',
    FACEBOOK_PAGE_ID = '403046706229851',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'noticiashorizonte';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_PULSODIARIO',
    FACEBOOK_PAGE_ID = '429372300256610',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'pulsodiario';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_PUNTOCLAVE',
    FACEBOOK_PAGE_ID = '497685936753403',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'puntoclave';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_PUNTONOTICIAS',
    FACEBOOK_PAGE_ID = '216140764924862',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'puntonoticias';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_RADARINFORMATIVO',
    FACEBOOK_PAGE_ID = '405301062674763',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'radarinformativo';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_REPORTEDIARIO',
    FACEBOOK_PAGE_ID = '274537812414282',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'reportediario';

UPDATE SITIOS SET 
    FACEBOOK_TOKEN_SECRET = 'FB_TOKEN_TELEVISIONABC',
    FACEBOOK_PAGE_ID = '481562451709320',
    FACEBOOK_ACTIVO = 1
WHERE SLUG = 'televisionabc';

-- Verificar actualización
SELECT SLUG, NOMBRE, FACEBOOK_ACTIVO, FACEBOOK_PAGE_ID, FACEBOOK_TOKEN_SECRET 
FROM SITIOS 
WHERE FACEBOOK_ACTIVO = 1 
ORDER BY SLUG;
